import { fWspolne } from '../../../../POM/Funkcje wspolne/Funkcje wspolne'
import { e501 } from '../../../../POM/Produkcja/Wnioski o przydzielenie zasobow/E501 Wniosek o przydzielenie zasobów - wyszukiwarka'
import { e502 } from '../../../../POM/Produkcja/Wnioski o przydzielenie zasobow/E502 Wniosek o przydzielenie zasobów - szczegoly'
import { e50203 } from '../../../../POM/Produkcja/Wnioski o przydzielenie zasobow/E502.03 Masowe dodawanie rezerwacji'

describe('SEPP-18078 Masowe dodawanie rezerwacji', () => {
    it('Masowe dodawanie rezerwacji', () => {
        cy.log('Krok 1 - Loguję się jako Koordynator Usług (producent)')
        cy.visit('/')
            .loginKoordynatorUslug()

        cy.log('Krok 2 - Jestem na ekranie listy wniosków o zasoby i przechodzę na ekran edycji wybranego wniosku')
        cy.goToMenu('Wnioski o przydzielenie zasobów')
        e501.nazwaAudycjiTVPoleTekstowe().type('SEPP-18078')
        e501.wyszukajPrzycisk().click()
        fWspolne.sprawdzProgressBar()
        e501.edytujWniosekPierwszyPrzycisk().click()
        fWspolne.sprawdzProgressBar()

        cy.log('Krok 3 - Jestem na ekranie edycji wniosku o zasoby i dodaje masowo rezerwację w trybie dziennym')
        e502.masoweDodawanieRezerwacjiPrzycisk().click()
        e50203.sekcjaWnioskuLista().select('Technika studyjna', {force: true})
        e50203.odDniaData().type('30.06.2025')
        e50203.czestotliwoscRadio('Dzień').click()
        e50203.doDniaData().type('01.07.2025')
        cy.get('#select2-ExecutionPlacesId-container').click()
        cy.get('.select2-search__field').type('Studio S1')
        cy.get('.select2-results__option--highlighted').should('contain', 'Studio S1').click()
        e50203.potwierdzPrzycisk().click()
        cy.get('#sectionTable_table > tbody').should('have.prop', 'childElementCount', 2)

        cy.log('Krok 4 - Usuwam dodane rezerwacje')
        e502.usunRezerwacjePierwszyPrzycisk().click()
        e502.usunAnulujPopupPrzycisk().click()
        fWspolne.sprawdzProgressBar()
        cy.get('#sectionTable_table > tbody').should('have.prop', 'childElementCount', 1)
        e502.usunRezerwacjePierwszyPrzycisk().click()
        e502.usunAnulujPopupPrzycisk().click()

        cy.log('Krok 5 - Jestem na ekranie edycji wniosku o zasoby i dodaje masowo rezerwację w trybie tygodniowym')
        e502.masoweDodawanieRezerwacjiPrzycisk().click()
        e50203.sekcjaWnioskuLista().select('Montaż', {force: true})
        e50203.odDniaData().type('4.08.2025')
        e50203.czestotliwoscRadio('Tydzień').click()
        e50203.doDniaData().type('11.08.2025')
        cy.get('#select2-ExecutionPlacesId-container').click()
        cy.get('.select2-search__field').type('Montaż Final Cut (FC)')
        cy.get('.select2-results__option--highlighted').should('contain', 'Montaż Final Cut (FC)').click()
        e50203.dniTygodniaPrzyciskWyboru('Wtorek').uncheck()
        e50203.dniTygodniaPrzyciskWyboru('Środa').uncheck()
        e50203.dniTygodniaPrzyciskWyboru('Piątek').uncheck()
        e50203.dniTygodniaPrzyciskWyboru('Sobota').uncheck()
        e50203.dniTygodniaPrzyciskWyboru('Niedziela').uncheck()
        e50203.potwierdzPrzycisk().click()
        cy.get('#sectionTable_table > tbody').should('have.prop', 'childElementCount', 3)

        cy.log('Krok 6 - Usuwam dodane rezerwacje')
        e502.usunRezerwacjePierwszyPrzycisk().click()
        e502.usunAnulujPopupPrzycisk().click()
        fWspolne.sprawdzProgressBar()
        cy.get('#sectionTable_table > tbody').should('have.prop', 'childElementCount', 2)
        e502.usunRezerwacjePierwszyPrzycisk().click()
        e502.usunAnulujPopupPrzycisk().click()
        fWspolne.sprawdzProgressBar()
        cy.get('#sectionTable_table > tbody').should('have.prop', 'childElementCount', 1)
        e502.usunRezerwacjePierwszyPrzycisk().click()
        e502.usunAnulujPopupPrzycisk().click()
        fWspolne.sprawdzProgressBar()

        cy.log('Wylogowuję się')
        cy.logoutUser()
    })
})