import { DateTime } from 'luxon'
import { e50200 } from '../../../../POM/Produkcja/Wnioski o przydzielenie zasobow/E502.00 Wniosek o przydzielenie zasobow - wykorzystanie zasobow'
import { e50212 } from '../../../../POM/Produkcja/Wnioski o przydzielenie zasobow/E502.12 Wybor pozycji cennikowej'
import { fWspolne } from '../../../../POM/Funkcje wspolne/Funkcje wspolne'
import { e501 } from '../../../../POM/Produkcja/Wnioski o przydzielenie zasobow/E501 Wniosek o przydzielenie zasobów - wyszukiwarka'
import { e502 } from '../../../../POM/Produkcja/Wnioski o przydzielenie zasobow/E502 Wniosek o przydzielenie zasobów - szczegoly'
import { e50201 } from '../../../../POM/Produkcja/Wnioski o przydzielenie zasobow/E502.01 Wniosek o przydzielenie zasobow - szczegoly rezerwacji'

describe('SEPP-16913 Zamiana rezerwacji wstępnej w zamówienie', () => {

    const jutro = DateTime.now().plus({days:1}).toFormat('dd.MM.yyyy')
    afterEach('Wylogowanie', () => {
        cy.logoutUser()
    })
    
    it('Dodanie rezerwacji dla audycji ze starego porozumienia', () => {   
        cy.log('Krok 1 - Loguję się jako Producent')
        cy.visit('')
            .loginProducent()
    
        cy.log('Krok 2 - Jestem na ekranie listy wniosków o zasoby i przechodzę na ekran edycji wybranego wniosku')
        cy.goToMenu('Wnioski o przydzielenie zasobów')
        fWspolne.sprawdzProgressBar()
        e501.nazwaAudycjiTVPoleTekstowe().type('ANIOŁ PAŃSKI (LUTY-CZERWIEC 2021)')
        e501.ukryjZrealizowanePrzyciskWyboru().uncheck()
        e501.wyszukajPrzycisk().click()
        fWspolne.sprawdzProgressBar()
        e501.edytujWniosekPierwszyPrzycisk().click()

        cy.log('Krok 3 - Jestem na ekranie edycji wniosku o zasoby i dodaję nową rezerwację wstępną')
        e502.dodajRezerwacjePrzycisk().click()
        e50201.sekcjaLista().select('Technika studyjna', {force: true})
        e50201.dataRealizacjiOdData().type(jutro)
        e50201.dataRealizacjiDoData().type(jutro)
        e50201.miejsceRealizacjiLista().focus()
        e50201.zaznaczPierwszyDzienPrzyciskWyboru().check()
        e50201.zapiszPrzycisk().click()
        fWspolne.sprawdzProgressBar()
        e50201.audycjePierwszyPrzycisk().click()
        e50201.audycjaPierwszyPrzyciskWyboru().check()
        e50201.potwierdzAudycjePopupPrzycisk().click()
        fWspolne.sprawdzProgressBar()
        cy.get('.w3-text-blue').should('be.visible')
        e50201.zasobyPierwszyPrzycisk().click()
        e50200.dodajStanowiskoPrzycisk().click()
        e50212.nazwaPoleTekstowe().type('RTW - operator CG')
        e50212.wyszukajPrzycisk().click()
        fWspolne.sprawdzProgressBar()
        e50212.zaznaczPozycjeCennikowaPierwszyPrzyciskWyboru().check()
        e50212.zatwierdzPrzycisk().click()
        e50200.godzinaRozpoczeciaStanPierwszaData().type('10')
        e50200.godzinaZakonczeniaStanPierwszaData().type('20')
        e50200.dodajSprzetPrzycisk().click()
        e50200.sprzetPierwszaLista().select('Studio średnie - reżyserka (180,00 zł. / godzina)', {force: true})
        e50200.godzinaRozpoczeciaSprzetPierwszaData().type('10')
        e50200.godzinaZakonczeniaSprzetPierwszaData().type('20')
        e50200.zapiszPrzycisk().click()
        fWspolne.sprawdzProgressBar()
        e50200.wstepnaRezerwacjaPrzycisk().click()
        e50200.takWstepnaPopupPrzycisk().click()
        fWspolne.sprawdzProgressBar()
        e50200.modyfikujRezerwacjePrzycisk().click()
        e50201.statusRezerwacjiEtykieta().should('have.value', 'Przekazano do dyspozytury (rezerwacja wstępna)')
    })

    it('Dodanie rezerwacji dla audycji ze nowego porozumienia', () => {   
        cy.log('Krok 4 - Loguję się jako Producent')
        cy.visit('')
            .loginProducent()

        cy.log('Krok 5 - Jestem na ekranie listy wniosków o zasoby i przechodzę na ekran edycji wybranego wniosku')
        cy.goToMenu('Wnioski o przydzielenie zasobów')
        fWspolne.sprawdzProgressBar()
        e501.nazwaAudycjiTVPoleTekstowe().type('SEPP-16913')
        e501.ukryjZrealizowanePrzyciskWyboru().uncheck()
        e501.wyszukajPrzycisk().click()
        fWspolne.sprawdzProgressBar()
        e501.edytujWniosekPierwszyPrzycisk().click()

        cy.log('Krok 6 - Jestem na ekranie edycji wniosku o zasoby i dodaję nową rezerwację wstępną')
        e502.dodajRezerwacjePrzycisk().click()
        e50201.sekcjaLista().select('Technika studyjna', {force: true})
        e50201.dataRealizacjiOdData().type(jutro)
        e50201.dataRealizacjiDoData().type(jutro)
        e50201.miejsceRealizacjiLista().select('hala ATM A', {force: true})
        e50201.zaznaczPierwszyDzienPrzyciskWyboru().check()
        e50201.zapiszPrzycisk().click()
        fWspolne.sprawdzProgressBar()
        e50201.audycjePierwszyPrzycisk().click()
        e50201.audycjaPierwszyPrzyciskWyboru().check()
        e50201.potwierdzAudycjePopupPrzycisk().click()
        fWspolne.sprawdzProgressBar()
        cy.get('.w3-text-blue').should('be.visible')
        e50201.zasobyPierwszyPrzycisk().click()
        e50200.dodajStanowiskoPrzycisk().click()
        e50212.nazwaPoleTekstowe().type('RTW - operator CG')
        e50212.wyszukajPrzycisk().click()
        fWspolne.sprawdzProgressBar()
        e50212.zaznaczPozycjeCennikowaPierwszyPrzyciskWyboru().check()
        e50212.zatwierdzPrzycisk().click()
        e50200.godzinaRozpoczeciaStanPierwszaData().type('10')
        e50200.godzinaZakonczeniaStanPierwszaData().type('20')
        e50200.dodajSprzetPrzycisk().click()
        e50200.sprzetPierwszaLista().select('Nagłośnienie (25,00 zł. / godzina)', {force: true})
        e50200.godzinaRozpoczeciaSprzetPierwszaData().type('10')
        e50200.godzinaZakonczeniaSprzetPierwszaData().type('20')
        e50200.zapiszPrzycisk().click()
        fWspolne.sprawdzProgressBar()
        e50200.wstepnaRezerwacjaPrzycisk().click()
        e50200.takWstepnaPopupPrzycisk().click()
        fWspolne.sprawdzProgressBar()
        e50200.modyfikujRezerwacjePrzycisk().click()
        e50201.statusRezerwacjiEtykieta().should('have.value', 'Przekazano do dyspozytury (rezerwacja wstępna)')
    })

    it('Akceptacja obu utworzonych rezerwacji wstępnych', () => {   
        cy.log('Krok 7 - Loguję się jako Pracownik Dyspozytury')
        cy.visit('')
            .loginPracownikDyspozytury()
        
        cy.log('Krok 8 - Jestem na ekranie listy wniosków o zasoby i przechodzę na ekran szczegółów rezerwacji wstępnej dla audycji ze starego porozumienia')
        cy.goToMenu('Wnioski o przydzielenie zasobów')
        fWspolne.sprawdzProgressBar()
        e501.nazwaAudycjiTVPoleTekstowe().type('ANIOŁ PAŃSKI (LUTY-CZERWIEC 2021)')
        e501.statusRezerwacjiLista().select('Przekazano do dyspozytury (rezerwacja wstępna)', {force: true})
        e501.wyszukajPrzycisk().click()
        fWspolne.sprawdzProgressBar()
        e501.edytujSekcjeWnioskuPierwszyPrzycisk().click()

        cy.log('Krok 9 - Jestem na ekranie szczegółów rezerwacji wstępnej i wstępnie ją akceptuję')
        e50200.wstepnieZaakceptujPrzycisk().click()
        e50200.takWstepnieZaakceptujPopupPrzycisk().click()
        fWspolne.sprawdzProgressBar()
        e50200.modyfikujRezerwacjePrzycisk().click()
        e50201.statusRezerwacjiEtykieta().should('have.value', 'Rezerwacja wstępna')

        cy.log('Krok 10 - Powracam na ekranie listy wniosków o zasoby i przechodzę na ekran szczegółów rezerwacji wstępnej dla audycji z nowego porozumienia')
        cy.goToMenu('Wnioski o przydzielenie zasobów')
        fWspolne.sprawdzProgressBar()
        e501.nazwaAudycjiTVPoleTekstowe().clear().type('SEPP-16913')
        e501.statusRezerwacjiLista().select('Przekazano do dyspozytury (rezerwacja wstępna)', {force: true})
        e501.wyszukajPrzycisk().click()
        fWspolne.sprawdzProgressBar()
        e501.edytujSekcjeWnioskuPierwszyPrzycisk().click()

        cy.log('Krok 11 - Jestem na ekranie szczegółów rezerwacji wstępnej i wstępnie ją akceptuję')
        e50200.wstepnieZaakceptujPrzycisk().click()
        e50200.takWstepnieZaakceptujPopupPrzycisk().click()
        fWspolne.sprawdzProgressBar()
        e50200.modyfikujRezerwacjePrzycisk().click()
        e50201.statusRezerwacjiEtykieta().should('have.value', 'Rezerwacja wstępna')
    })

    it('Złożenie zamówienia na obu rezerwacjach wstępnych', () => {   
        cy.log('Krok 12 - Loguję się jako Producent')
        cy.visit('')
            .loginProducent()
            
        cy.log('Krok 13 - Jestem na ekranie listy wniosków o zasoby i przechodzę na ekran szczegółów rezerwacji wstępnej dla audycji ze starego porozumienia')
        cy.goToMenu('Wnioski o przydzielenie zasobów')
        fWspolne.sprawdzProgressBar()
        e501.nazwaAudycjiTVPoleTekstowe().type('ANIOŁ PAŃSKI (LUTY-CZERWIEC 2021)')
        e501.statusRezerwacjiLista().select('Rezerwacja wstępna', {force: true})
        e501.wyszukajPrzycisk().click()
        fWspolne.sprawdzProgressBar()
        e501.edytujSekcjeWnioskuPierwszyPrzycisk().click()

        cy.log('Krok 14 - Jestem na ekranie szczegółów rezerwacji wstępnej i składam zamówienie')
        e50200.zlozZamowieniePrzycisk().click()
        e50200.takZlozPopupPrzycisk().click()
        e50200.sprawdzPrzekroczenieCzasuZasobow()
        /*
        e50200.modyfikujRezerwacjePrzycisk().click()
        e50201.statusRezerwacjiEtykieta().should('have.value', 'Przekazano do dyspozytury (zamówienie)')
        */
        cy.log('Krok 15 - Jestem na ekranie listy wniosków o zasoby i przechodzę na ekran szczegółów rezerwacji wstępnej dla audycji z nowego porozumienia')
        cy.goToMenu('Wnioski o przydzielenie zasobów')
        fWspolne.sprawdzProgressBar()
        e501.nazwaAudycjiTVPoleTekstowe().clear().type('SEPP-16913')
        e501.statusRezerwacjiLista().select('Rezerwacja wstępna', {force: true})
        e501.wyszukajPrzycisk().click()
        fWspolne.sprawdzProgressBar()
        e501.edytujSekcjeWnioskuPierwszyPrzycisk().click()

        cy.log('Krok 16 - Jestem na ekranie szczegółów rezerwacji wstępnej i składam zamówienie')
        e50200.zlozZamowieniePrzycisk().click()
        e50200.takZlozPopupPrzycisk().click()
        e50200.sprawdzPrzekroczenieCzasuZasobow()
        /*
        e50200.modyfikujRezerwacjePrzycisk().click()
        e50201.statusRezerwacjiEtykieta().should('have.value', 'Przekazano do dyspozytury (zamówienie)')
        */
    })

    it('Przekształcenie rezerwacji wstępnych w zamówienie - akceptacja Dyspozytury', () => {   
        cy.log('Krok 17 - Loguję się jako Pracownik Dyspozytury')
        cy.visit('')
            .loginPracownikDyspozytury()
            
        cy.log('Krok 18 - Jestem na ekranie listy wniosków o zasoby i przechodzę na ekran szczegółów rezerwacji wstępnej przekazanej do realizacji dla audycji ze starego porozumienia')
        cy.goToMenu('Wnioski o przydzielenie zasobów')
        fWspolne.sprawdzProgressBar()
        e501.nazwaAudycjiTVPoleTekstowe().type('ANIOŁ PAŃSKI (LUTY-CZERWIEC 2021)')
        e501.statusRezerwacjiLista().select('Przekazano do dyspozytury (zamówienie)', {force: true})
        e501.wyszukajPrzycisk().click()
        fWspolne.sprawdzProgressBar()
        e501.edytujSekcjeWnioskuPierwszyPrzycisk().click()

        cy.log('Krok 19 - Jestem na ekranie szczegółów rezerwacji i ją akceptuję')
        e50200.zaakceptujPrzycisk().click()
        e50200.takZaakceptujPrzycisk().click()
        fWspolne.sprawdzProgressBar()
        e50200.modyfikujRezerwacjePrzycisk().click()
        e50201.statusRezerwacjiEtykieta().should('have.value', 'Do realizacji')

        cy.log('Krok 20 - Jestem na ekranie listy wniosków o zasoby i przechodzę na ekran szczegółów rezerwacji wstępnej przekazanej do realizacji dla audycji z nowego porozumienia')
        cy.goToMenu('Wnioski o przydzielenie zasobów')
        fWspolne.sprawdzProgressBar()
        e501.nazwaAudycjiTVPoleTekstowe().clear().type('SEPP-16913')
        e501.statusRezerwacjiLista().select('Przekazano do dyspozytury (zamówienie)', {force: true})
        e501.wyszukajPrzycisk().click()
        fWspolne.sprawdzProgressBar()
        e501.edytujSekcjeWnioskuPierwszyPrzycisk().click()

        cy.log('Krok 21 - Jestem na ekranie szczegółów rezerwacji i ją akceptuję')
        e50200.zaakceptujPrzycisk().click()
        e50200.takZaakceptujPrzycisk().click()
        fWspolne.sprawdzProgressBar()
        e50200.modyfikujRezerwacjePrzycisk().click()
        e50201.statusRezerwacjiEtykieta().should('have.value', 'Zamówienie wstępnie zaakceptowane')
    })
})