import { fWspolne } from '../../../../POM/Funkcje wspolne/Funkcje wspolne'
import { e503 } from '../../../../POM/Produkcja/Planowanie produkcji/E503 Planowanie produkcji'
import { e501 } from '../../../../POM/Produkcja/Wnioski o przydzielenie zasobow/E501 Wniosek o przydzielenie zasobów - wyszukiwarka'
import { e502 } from '../../../../POM/Produkcja/Wnioski o przydzielenie zasobow/E502 Wniosek o przydzielenie zasobów - szczegoly'
import { e50200 } from '../../../../POM/Produkcja/Wnioski o przydzielenie zasobow/E502.00 Wniosek o przydzielenie zasobow - wykorzystanie zasobow'
import { e50201 } from '../../../../POM/Produkcja/Wnioski o przydzielenie zasobow/E502.01 Wniosek o przydzielenie zasobow - szczegoly rezerwacji'
import { e50212 } from '../../../../POM/Produkcja/Wnioski o przydzielenie zasobow/E502.12 Wybor pozycji cennikowej'

describe('SEPP-16288 Wyświetlanie uwag', () => {

    it('Wyświetlanie uwag z kosztorysu', () => {
        cy.log('Krok 1 - Loguję się jako Producent')
        cy.visit('')
            .loginProducent()

        cy.log('Krok 2 - Przechodzę na ekran Wniosków o zasoby i wyszukuję wybrany wniosek')
        cy.goToMenu('Wnioski o przydzielenie zasobów')
        fWspolne.sprawdzProgressBar()
        e501.nazwaAudycjiTVPoleTekstowe().type('SEPP-16288')
        e501.pokazZdjeteZAntenyPrzyciskWyboru().check()
        e501.wyszukajPrzycisk().click()
        fWspolne.sprawdzProgressBar()
        e501.edytujWniosekPierwszyPrzycisk().click()

        cy.log('Krok 3 - Dodaję nową rezerwację')
        e502.dodajRezerwacjePrzycisk().click()
        e50201.sekcjaLista().select('Technika studyjna', {force: true})
        e50201.miejsceRealizacjiLista().select('hala ATM A', {force: true})
        e50201.dataRealizacjiOdData().type('30.06.2024')
        e50201.dataRealizacjiDoData().type('30.06.2024')
        e50201.uwagiDoRezerwacjiPoleTekstowe().type('Uwagi do rezerwacji przy tworzeniu rezerwacji')
        e50201.zaznaczPierwszyDzienPrzyciskWyboru().check()
        e50201.zapiszPrzycisk().click()
        e50201.audycjePierwszyPrzycisk().click()
        e50201.audycjaPierwszyPrzyciskWyboru().check()
        e50201.potwierdzAudycjePopupPrzycisk().click()
        fWspolne.sprawdzProgressBar()

        cy.log('Krok 4 - Wypełniam rezerwację pobierając zasoby z kosztorysu i składam zamówienie')
        e50201.zasobyPierwszyPrzycisk().click({force: true})
        e50200.pobierzZKosztorysuSprzetPrzycisk().click()
        e50200.takPobierzPopupPrzycisk().click()
        e50200.uwagiSprzetPierwszePoleTekstowe().should('have.value', 'komentarz dla sprzętu w kosztorysie')
        e50200.godzinaRozpoczeciaSprzetPierwszaData().type('8')
        e50200.godzinaZakonczeniaSprzetPierwszaData().type('16')
        e50200.dodajStanowiskoPrzycisk().click()
        e50212.zaznaczPozycjeCennikowaPierwszyPrzyciskWyboru().check()
        e50212.zatwierdzPrzycisk().click()
        e50200.uwagiStanPierwszePoleTekstowe().should('have.value', 'komentarz dla usługi w kosztorysie')
        e50200.godzinaRozpoczeciaStanPierwszaData().type('8')
        e50200.godzinaZakonczeniaStanPierwszaData().type('16')
        e50200.zapiszPrzycisk().click()
        e50200.zlozZamowieniePrzycisk().click()
        e50200.takZlozPopupPrzycisk().click()

        cy.log('Wylogowuję się')
        cy.logoutUser()
    })

    it('Wyswietlanie uwag do zasobów na diagramie Gantta', () => {
        cy.log('Krok 5 - Loguję się jako Pracownik Dyspozytury')
        cy.visit('')
            .loginPracownikDyspozytury()

        cy.log('Krok 6 - Przechodzę na ekran Wniosków o zasoby i wyszukuję wybrany wniosek')
        cy.goToMenu('Wnioski o przydzielenie zasobów')
        fWspolne.sprawdzProgressBar()
        e501.nazwaAudycjiTVPoleTekstowe().type('SEPP-16288')
        e501.wyszukajPrzycisk().click()
        fWspolne.sprawdzProgressBar()

        cy.log('Krok 7 - Akceptuję zamówienie')
        e501.edytujSekcjeWnioskuPierwszyPrzycisk().click()
        e50200.uwagiSprzetPierwszePoleTekstowe().should('have.value', 'komentarz dla sprzętu w kosztorysie')
        e50200.uwagiStanPierwszePoleTekstowe().should('have.value', 'komentarz dla usługi w kosztorysie')
        e50200.zaakceptujPrzycisk().click()
        e50200.takZaakceptujPrzycisk().click()
        fWspolne.sprawdzProgressBar()

        cy.log('Krok 8 - Przechodzę na ekran Planowania produkcji i wyszukuję zasoby z wybranego zamówienia')
        cy.goToMenu('Planowanie produkcji')
        fWspolne.sprawdzProgressBar()
        e503.zwinRozwinFiltryPrzycisk().click()
        e503.tytulAudycjiTVPoleTestowe().type('SEPP-16288')
        cy.get('.select2-results__option').should('contain', 'SEPP-16288')
        e503.tytulAudycjiTVPoleTestowe().type('{enter}')
        e503.przedzialCzasuPrzycisk().click()
        e503.wybierzMiesiacPopupPrzycisk().click()
        e503.wybierzRokPopupPrzycisk().click()
        cy.get('.year').contains('2024').click()
        cy.get('.month').contains('cze').click()
        cy.get('[data-day="30.06.2024"]').click()
        e503.wyszukajDatePopupPrzycisk().click()

        cy.log('Krok 9 - Dodaję pracownika i element sprzętowy wraz z uwagami')
        cy.get('[title="Nagłośnienie"]').click()
        e503.dodajElementSprzetowyPrzycisk().click()
        cy.get('[type="checkbox"]').eq(1).check()
        cy.get('input#Comments').type('uwagi dla pracownika w trakcie dodawania sprzętu przez dyspozytora')
        cy.get('button#saveBtn').click()
        fWspolne.sprawdzProgressBar()
        cy.get('a.btn-info').click()
        cy.get('[title="RTŚ - TECHNIK ŚWIATŁA"]').click()
        e503.dodajPracownikaPrzycisk().click()
        cy.get('[type="checkbox"]').eq(2).check()
        cy.get('input#Comments').type('uwagi dla pracownika w trakcie dodawania go przez dyspozytora')
        cy.get('button#saveBtn').click()
        fWspolne.sprawdzProgressBar()
        cy.get('a.btn-info').click()
        
        cy.log('Krok 10 - Weryfikuję wyświetlanie uwag dla zasobów')
        cy.get('.Gantt-event').contains('1 szt.').click()
        cy.get('.popover-buttons>div>.row').should('contain.text', 'uwagi dla pracownika w trakcie dodawania sprzętu przez dyspozytora')
        cy.get('[style*="background: rgb(94, 159, 223)"]').click() // gwiazdka przy 'style' oznacza 'contains' dla danego atrybutu
        cy.get('.popover-buttons>div>.row').should('contain.text', 'komentarz dla sprzętu w kosztorysie')
        cy.get('[style*="background: repeating-linear-gradient(45deg, rgb(255, 243, 204)"]').click()
        cy.get('.popover-buttons>div>.row').should('contain.text', 'uwagi dla pracownika w trakcie dodawania go przez dyspozytora')
        cy.get('[style*="background: rgb(238, 125, 45)"]').click()
        cy.get('.popover-buttons>div>.row').should('contain.text', 'komentarz dla usługi w kosztorysie')

        cy.log('Krok 11 - Anuluje rezerwację w celu replikowalności testu')
        cy.goToMenu('Wnioski o przydzielenie zasobów')
        e501.edytujWniosekPierwszyPrzycisk().click()
        e502.usunRezerwacjePierwszyPrzycisk().click()
        e502.powodAnulacjiPopupPoleTekstowe().type('anuluję rezerwację')
        e502.usunAnulujPopupPrzycisk().click()

        cy.log('Wylogowuję się')
        cy.logoutUser()
    })
})