import { fWspolne } from '../../../../POM/Funkcje wspolne/Funkcje wspolne'
import { e20 } from '../../../../POM/Planowanie/E20 Porozumienia'
import { e22 } from '../../../../POM/Planowanie/E22 Porozumienia - szczegoly'
import { e224 } from '../../../../POM/Planowanie/E224 Dodawanie i edycja wskaznikow'

describe('SEPP-18054 Wyliczenia dla audycji TV - PW', () => {
    it('Wyliczenia dla audycji TV - PW', () => {
        cy.log('Krok 1 - Loguję się jako Producent')
        cy.visit('/')
            .loginProducent()

        cy.log('Krok 2 - Jestem na ekranie listy porozumień i przechodzę na ekran edycji wybranego porozumienia')
        cy.goToMenu('Porozumienia')
        e20.nazwaAudycjiTVPoleTekstowe().type('SEPP-18054')
        e20.wyszukajPrzycisk().click()
        fWspolne.sprawdzProgressBar()
        e20.edycjaPierwszyPrzycisk().click()
        fWspolne.sprawdzProgressBar()

        cy.log('Krok 3 - Weryfikuję istniejące dane porozumienia')
        // Liczba odcinków
        e22.liczbaOdcinkowPoleTekstowe().should('have.attr', 'value', 1)
        // Kwoty cyklu
        e22.cenaSprzedazySumarycznaPoleTekstowe().should('have.attr', 'value', '29514,24')
        e22.wartoscPrawNabytychPoleTekstowe().should('have.attr', 'value', '0,00')
        e22.przeniesieniePrawMajatkowychLista().find('option[selected]').contains('Wartość praw podlega amortyzacji')
        e22.wartoscMaterialowArchiwalnychPoleTekstowe().should('have.attr', 'value', '0,00')
        e22.wynagrodzeniePracowniczePoleTekstowe().should('have.attr', 'value', '500,00')
        e22.wynagrodzenieWspolpracowniczePoleTekstowe().should('have.attr', 'value', '23000,00')
        e22.wartFinansZInJednPoleTekstowe().should('have.attr', 'value', '0,00')
        // Zestawienie zbiorcze kosztów jednostki TVP S.A.
        e22.pochodneOdWynagrodzenPoleTekstowe().should('have.attr', 'value', '47,50')
        e22.kosztyZewnetrznePoleTekstowe().should('have.attr', 'value', '14757,12')
        e22.kosztyBezposredniePoleTekstowe().should('have.attr', 'value', '29514,24')
        e22.kosztyPosredniePoleTekstowe().should('have.attr', 'value', '0,00')
        e22.kosztyRazemPoleTekstowe().should('have.attr', 'value', '29514,24')
        e22.kosztCalkNettoPoleTekstowe().should('have.attr', 'value', '29514,24')
        e22.vatPoleTekstowe().should('have.attr', 'value', '0,00')
        e22.vatOdPrawPoleTekstowe().should('have.attr', 'value', '0,00')
        e22.cenaSprzedazyPoleTekstowe().should('have.attr', 'value', '29514,24')
        // Wskaźniki
        e22.edytujWskaznikiPrzycisk().click()
        e224.jednostkaRozliczeniowaPoleTekstowe().siblings('input.form-control').should('have.attr', 'value', 'Jedn.Koszt.TVP')
        e224.narzutKosztowPosrPoleTekstowe().should('have.attr', 'value', '0,00')
        e224.vatPZPoleTekstowe().should('have.attr', 'value', '0,00')
        e224.vatWKosztachPoleTekstowe().should('have.prop', 'value', '69,74 %')
        e224.zusOdWynagrodzenPoleTekstowe().should('have.prop', 'value', '19,00 %')
        e224.sredniaOdWynagrodzenPoleTekstowe().should('have.attr', 'value', '0,00')
        e224.vatOdPrawPoleTekstowe().should('have.prop', 'value', '23,00 %')
        e224.powrotPrzycisk().click()

        cy.log('Krok 4 - Zmieniam liczbę odcinków i weryfikuję dane porozumienia')
        e22.liczbaOdcinkowPoleTekstowe().clear().type('10')
        e22.zapiszPrzycisk().click()
        e22.potwierdzLiczbeOdcinkowPopupPrzycisk().click()
        fWspolne.sprawdzProgressBar()
        // Liczba odcinków
        e22.liczbaOdcinkowPoleTekstowe().should('have.attr', 'value', 10)
        // Kwoty cyklu
        e22.cenaSprzedazySumarycznaPoleTekstowe().should('have.attr', 'value', '86270,10')
        e22.wartoscPrawNabytychPoleTekstowe().should('have.attr', 'value', '0,00')
        e22.przeniesieniePrawMajatkowychLista().find('option[selected]').contains('Wartość praw podlega amortyzacji')
        e22.wartoscMaterialowArchiwalnychPoleTekstowe().should('have.attr', 'value', '0,00')
        e22.wynagrodzeniePracowniczePoleTekstowe().should('have.attr', 'value', '500,00')
        e22.wynagrodzenieWspolpracowniczePoleTekstowe().should('have.attr', 'value', '23000,00')
        e22.wartFinansZInJednPoleTekstowe().should('have.attr', 'value', '0,00')
        // Zestawienie zbiorcze kosztów jednostki TVP S.A.
        e22.pochodneOdWynagrodzenPoleTekstowe().should('have.attr', 'value', '47,50')
        e22.kosztyZewnetrznePoleTekstowe().should('have.attr', 'value', '4313,50')
        e22.kosztyBezposredniePoleTekstowe().should('have.attr', 'value', '8627,00')
        e22.kosztyPosredniePoleTekstowe().should('have.attr', 'value', '0,00')
        e22.kosztyRazemPoleTekstowe().should('have.attr', 'value', '8627,00')
        e22.kosztCalkNettoPoleTekstowe().should('have.attr', 'value', '8627,00')
        e22.vatPoleTekstowe().should('have.attr', 'value', '0,00')
        e22.vatOdPrawPoleTekstowe().should('have.attr', 'value', '0,00')
        e22.cenaSprzedazyPoleTekstowe().should('have.attr', 'value', '8627,00')
        // Wskaźniki
        e22.edytujWskaznikiPrzycisk().click()
        e224.jednostkaRozliczeniowaPoleTekstowe().siblings('input.form-control').should('have.attr', 'value', 'Jedn.Koszt.TVP')
        e224.narzutKosztowPosrPoleTekstowe().should('have.attr', 'value', '0,00')
        e224.vatPZPoleTekstowe().should('have.attr', 'value', '0,00')
        e224.vatWKosztachPoleTekstowe().should('have.prop', 'value', '69,74 %')
        e224.zusOdWynagrodzenPoleTekstowe().should('have.prop', 'value', '19,00 %')
        e224.sredniaOdWynagrodzenPoleTekstowe().should('have.attr', 'value', '0,00')
        e224.vatOdPrawPoleTekstowe().should('have.prop', 'value', '23,00 %')
        e224.powrotPrzycisk().click()

        cy.log('Krok 5 - Zmieniam wartość praw nabytych i weryfikuję dane porozumienia')
        e22.wartoscPrawNabytychPoleTekstowe().clear().type('1000')
        e22.zapiszPrzycisk().click()
        fWspolne.sprawdzProgressBar()
        // Liczba odcinków
        e22.liczbaOdcinkowPoleTekstowe().should('have.attr', 'value', 10)
        // Kwoty cyklu
        e22.cenaSprzedazySumarycznaPoleTekstowe().should('have.attr', 'value', '85109,70')
        e22.wartoscPrawNabytychPoleTekstowe().should('have.attr', 'value', '1000,00')
        e22.przeniesieniePrawMajatkowychLista().find('option[selected]').contains('Wartość praw podlega amortyzacji')
        e22.wartoscMaterialowArchiwalnychPoleTekstowe().should('have.attr', 'value', '0,00')
        e22.wynagrodzeniePracowniczePoleTekstowe().should('have.attr', 'value', '500,00')
        e22.wynagrodzenieWspolpracowniczePoleTekstowe().should('have.attr', 'value', '23000,00')
        e22.wartFinansZInJednPoleTekstowe().should('have.attr', 'value', '0,00')
        // Zestawienie zbiorcze kosztów jednostki TVP S.A.
        e22.pochodneOdWynagrodzenPoleTekstowe().should('have.attr', 'value', '47,50')
        e22.kosztyZewnetrznePoleTekstowe().should('have.attr', 'value', '4313,50')
        e22.kosztyBezposredniePoleTekstowe().should('have.attr', 'value', '8627,00')
        e22.kosztyPosredniePoleTekstowe().should('have.attr', 'value', '0,00')
        e22.kosztyRazemPoleTekstowe().should('have.attr', 'value', '8627,00')
        e22.kosztCalkNettoPoleTekstowe().should('have.attr', 'value', '8627,00')
        e22.vatPoleTekstowe().should('have.attr', 'value', '0,00')
        e22.vatOdPrawPoleTekstowe().should('have.attr', 'value', '16,04')
        e22.cenaSprzedazyPoleTekstowe().should('have.attr', 'value', '8510,96')
        // Wskaźniki
        e22.edytujWskaznikiPrzycisk().click()
        e224.jednostkaRozliczeniowaPoleTekstowe().siblings('input.form-control').should('have.attr', 'value', 'Jedn.Koszt.TVP')
        e224.narzutKosztowPosrPoleTekstowe().should('have.attr', 'value', '0,00')
        e224.vatPZPoleTekstowe().should('have.attr', 'value', '0,00')
        e224.vatWKosztachPoleTekstowe().should('have.prop', 'value', '69,74 %')
        e224.zusOdWynagrodzenPoleTekstowe().should('have.prop', 'value', '19,00 %')
        e224.sredniaOdWynagrodzenPoleTekstowe().should('have.attr', 'value', '0,00')
        e224.vatOdPrawPoleTekstowe().should('have.prop', 'value', '23,00 %')
        e224.powrotPrzycisk().click()

        cy.log('Krok 6 - Zmieniam wartość praw mat. arch. i weryfikuję dane porozumienia')
        e22.wartoscMaterialowArchiwalnychPoleTekstowe().clear().type('1000')
        e22.zapiszPrzycisk().click()
        fWspolne.sprawdzProgressBar()
        // Liczba odcinków
        e22.liczbaOdcinkowPoleTekstowe().should('have.attr', 'value', 10)
        // Kwoty cyklu
        e22.cenaSprzedazySumarycznaPoleTekstowe().should('have.attr', 'value', '85109,70')
        e22.wartoscPrawNabytychPoleTekstowe().should('have.attr', 'value', '1000,00')
        e22.przeniesieniePrawMajatkowychLista().find('option[selected]').contains('Wartość praw podlega amortyzacji')
        e22.wartoscMaterialowArchiwalnychPoleTekstowe().should('have.attr', 'value', '1000,00')
        e22.wynagrodzeniePracowniczePoleTekstowe().should('have.attr', 'value', '500,00')
        e22.wynagrodzenieWspolpracowniczePoleTekstowe().should('have.attr', 'value', '23000,00')
        e22.wartFinansZInJednPoleTekstowe().should('have.attr', 'value', '0,00')
        // Zestawienie zbiorcze kosztów jednostki TVP S.A.
        e22.pochodneOdWynagrodzenPoleTekstowe().should('have.attr', 'value', '47,50')
        e22.kosztyZewnetrznePoleTekstowe().should('have.attr', 'value', '4313,50')
        e22.kosztyBezposredniePoleTekstowe().should('have.attr', 'value', '8627,00')
        e22.kosztyPosredniePoleTekstowe().should('have.attr', 'value', '0,00')
        e22.kosztyRazemPoleTekstowe().should('have.attr', 'value', '8627,00')
        e22.kosztCalkNettoPoleTekstowe().should('have.attr', 'value', '9627,00')
        e22.vatPoleTekstowe().should('have.attr', 'value', '0,00')
        e22.vatOdPrawPoleTekstowe().should('have.attr', 'value', '16,04')
        e22.cenaSprzedazyPoleTekstowe().should('have.attr', 'value', '8510,96')
        // Wskaźniki
        e22.edytujWskaznikiPrzycisk().click()
        e224.jednostkaRozliczeniowaPoleTekstowe().siblings('input.form-control').should('have.attr', 'value', 'Jedn.Koszt.TVP')
        e224.narzutKosztowPosrPoleTekstowe().should('have.attr', 'value', '0,00')
        e224.vatPZPoleTekstowe().should('have.attr', 'value', '0,00')
        e224.vatWKosztachPoleTekstowe().should('have.prop', 'value', '69,74 %')
        e224.zusOdWynagrodzenPoleTekstowe().should('have.prop', 'value', '19,00 %')
        e224.sredniaOdWynagrodzenPoleTekstowe().should('have.attr', 'value', '0,00')
        e224.vatOdPrawPoleTekstowe().should('have.prop', 'value', '23,00 %')
        e224.powrotPrzycisk().click()

        cy.log('Krok 7 - Zmieniam wartość finansowania z innych jednostek i weryfikuję dane porozumienia')
        e22.wartFinansZInJednPoleTekstowe().clear().type('1000')
        e22.zapiszPrzycisk().click()
        fWspolne.sprawdzProgressBar()
        // Liczba odcinków
        e22.liczbaOdcinkowPoleTekstowe().should('have.attr', 'value', 10)
        // Kwoty cyklu
        e22.cenaSprzedazySumarycznaPoleTekstowe().should('have.attr', 'value', '84109,70')
        e22.wartoscPrawNabytychPoleTekstowe().should('have.attr', 'value', '1000,00')
        e22.przeniesieniePrawMajatkowychLista().find('option[selected]').contains('Wartość praw podlega amortyzacji')
        e22.wartoscMaterialowArchiwalnychPoleTekstowe().should('have.attr', 'value', '1000,00')
        e22.wynagrodzeniePracowniczePoleTekstowe().should('have.attr', 'value', '500,00')
        e22.wynagrodzenieWspolpracowniczePoleTekstowe().should('have.attr', 'value', '23000,00')
        e22.wartFinansZInJednPoleTekstowe().should('have.attr', 'value', '1000,00')
        // Zestawienie zbiorcze kosztów jednostki TVP S.A.
        e22.pochodneOdWynagrodzenPoleTekstowe().should('have.attr', 'value', '47,50')
        e22.kosztyZewnetrznePoleTekstowe().should('have.attr', 'value', '4313,50')
        e22.kosztyBezposredniePoleTekstowe().should('have.attr', 'value', '8627,00')
        e22.kosztyPosredniePoleTekstowe().should('have.attr', 'value', '0,00')
        e22.kosztyRazemPoleTekstowe().should('have.attr', 'value', '8627,00')
        e22.kosztCalkNettoPoleTekstowe().should('have.attr', 'value', '9627,00')
        e22.vatPoleTekstowe().should('have.attr', 'value', '0,00')
        e22.vatOdPrawPoleTekstowe().should('have.attr', 'value', '16,04')
        e22.cenaSprzedazyPoleTekstowe().should('have.attr', 'value', '8410,96')
        // Wskaźniki
        e22.edytujWskaznikiPrzycisk().click()
        e224.jednostkaRozliczeniowaPoleTekstowe().siblings('input.form-control').should('have.attr', 'value', 'Jedn.Koszt.TVP')
        e224.narzutKosztowPosrPoleTekstowe().should('have.attr', 'value', '0,00')
        e224.vatPZPoleTekstowe().should('have.attr', 'value', '0,00')
        e224.vatWKosztachPoleTekstowe().should('have.prop', 'value', '69,74 %')
        e224.zusOdWynagrodzenPoleTekstowe().should('have.prop', 'value', '19,00 %')
        e224.sredniaOdWynagrodzenPoleTekstowe().should('have.attr', 'value', '0,00')
        e224.vatOdPrawPoleTekstowe().should('have.prop', 'value', '23,00 %')
        e224.powrotPrzycisk().click()

        cy.log('Krok 8 - Zmieniam wartość w polu Przeniesienie praw majątkowych i weryfikuję dane porozumienia')
        e22.przeniesieniePrawMajatkowychLista().select('Wartość praw nie podlega amortyzacji', {force: true})
        cy.wait(500)
        e22.potwierdzPrzeniesieniePrawPopupPrzycisk().should('be.visible').click()
        e22.potwierdzPrzeniesieniePrawPopupPrzycisk().should('not.be.visible')
        e22.zapiszPrzycisk().click()
        fWspolne.sprawdzProgressBar()
        // Liczba odcinków
        e22.liczbaOdcinkowPoleTekstowe().should('have.attr', 'value', 10)
        // Kwoty cyklu
        e22.cenaSprzedazySumarycznaPoleTekstowe().should('have.attr', 'value', '85270,10')
        e22.wartoscPrawNabytychPoleTekstowe().should('have.attr', 'value', '1000,00')
        e22.przeniesieniePrawMajatkowychLista().find('option[selected]').contains('Wartość praw nie podlega amortyzacji')
        e22.wartoscMaterialowArchiwalnychPoleTekstowe().should('have.attr', 'value', '1000,00')
        e22.wynagrodzeniePracowniczePoleTekstowe().should('have.attr', 'value', '500,00')
        e22.wynagrodzenieWspolpracowniczePoleTekstowe().should('have.attr', 'value', '23000,00')
        e22.wartFinansZInJednPoleTekstowe().should('have.attr', 'value', '1000,00')
        // Zestawienie zbiorcze kosztów jednostki TVP S.A.
        e22.pochodneOdWynagrodzenPoleTekstowe().should('have.attr', 'value', '47,50')
        e22.kosztyZewnetrznePoleTekstowe().should('have.attr', 'value', '4313,50')
        e22.kosztyBezposredniePoleTekstowe().should('have.attr', 'value', '8627,00')
        e22.kosztyPosredniePoleTekstowe().should('have.attr', 'value', '0,00')
        e22.kosztyRazemPoleTekstowe().should('have.attr', 'value', '8627,00')
        e22.kosztCalkNettoPoleTekstowe().should('have.attr', 'value', '9627,00')
        e22.vatPoleTekstowe().should('have.attr', 'value', '0,00')
        e22.vatOdPrawPoleTekstowe().should('have.attr', 'value', '16,04')
        e22.cenaSprzedazyPoleTekstowe().should('have.attr', 'value', '8527,00')
        // Wskaźniki
        e22.edytujWskaznikiPrzycisk().click()
        e224.jednostkaRozliczeniowaPoleTekstowe().siblings('input.form-control').should('have.attr', 'value', 'Jedn.Koszt.TVP')
        e224.narzutKosztowPosrPoleTekstowe().should('have.attr', 'value', '0,00')
        e224.vatPZPoleTekstowe().should('have.attr', 'value', '0,00')
        e224.vatWKosztachPoleTekstowe().should('have.prop', 'value', '69,74 %')
        e224.zusOdWynagrodzenPoleTekstowe().should('have.prop', 'value', '19,00 %')
        e224.sredniaOdWynagrodzenPoleTekstowe().should('have.attr', 'value', '0,00')
        e224.vatOdPrawPoleTekstowe().should('have.prop', 'value', '23,00 %')
        e224.powrotPrzycisk().click()

        cy.log('Krok 9 - Zmieniam wartość narzutu kosztów pośrednich we wskaźnikach i weryfikuję dane porozumienia')
        e22.edytujWskaznikiPrzycisk().click()
        e224.narzutKosztowPosrPoleTekstowe().clear().type('10')
        e224.zapiszPrzycisk().click()
        fWspolne.sprawdzProgressBar()
        // Liczba odcinków 
        e22.liczbaOdcinkowPoleTekstowe().should('have.attr', 'value', 10)
        // Kwoty cyklu
        e22.cenaSprzedazySumarycznaPoleTekstowe().should('have.attr', 'value', '93781,07')
        e22.wartoscPrawNabytychPoleTekstowe().should('have.attr', 'value', '1000,00')
        e22.przeniesieniePrawMajatkowychLista().find('option[selected]').contains('Wartość praw nie podlega amortyzacji')
        e22.wartoscMaterialowArchiwalnychPoleTekstowe().should('have.attr', 'value', '1000,00')
        e22.wynagrodzeniePracowniczePoleTekstowe().should('have.attr', 'value', '500,00')
        e22.wynagrodzenieWspolpracowniczePoleTekstowe().should('have.attr', 'value', '23000,00')
        e22.wartFinansZInJednPoleTekstowe().should('have.attr', 'value', '1000,00')
        // Zestawienie zbiorcze kosztów jednostki TVP S.A.
        e22.pochodneOdWynagrodzenPoleTekstowe().should('have.attr', 'value', '47,50')
        e22.kosztyZewnetrznePoleTekstowe().should('have.attr', 'value', '4313,50')
        e22.kosztyBezposredniePoleTekstowe().should('have.attr', 'value', '8627,00')
        e22.kosztyPosredniePoleTekstowe().should('have.attr', 'value', '851,10')
        e22.kosztyRazemPoleTekstowe().should('have.attr', 'value', '9478,10')
        e22.kosztCalkNettoPoleTekstowe().should('have.attr', 'value', '10478,10')
        e22.vatPoleTekstowe().should('have.attr', 'value', '0,00')
        e22.vatOdPrawPoleTekstowe().should('have.attr', 'value', '16,04')
        e22.cenaSprzedazyPoleTekstowe().should('have.attr', 'value', '9378,10')
        // Wskaźniki
        e22.edytujWskaznikiPrzycisk().click()
        e224.jednostkaRozliczeniowaPoleTekstowe().siblings('input.form-control').should('have.attr', 'value', 'Jedn.Koszt.TVP')
        e224.narzutKosztowPosrPoleTekstowe().should('have.prop', 'value', '10,00 %')
        e224.vatPZPoleTekstowe().should('have.attr', 'value', '0,00')
        e224.vatWKosztachPoleTekstowe().should('have.prop', 'value', '69,74 %')
        e224.zusOdWynagrodzenPoleTekstowe().should('have.prop', 'value', '19,00 %')
        e224.sredniaOdWynagrodzenPoleTekstowe().should('have.attr', 'value', '0,00')
        e224.vatOdPrawPoleTekstowe().should('have.prop', 'value', '23,00 %')
        e224.powrotPrzycisk().click()

        cy.log('Krok 10 - Zmieniam wartość vatu w kosztach we wskaźnikach i weryfikuję dane porozumienia')
        e22.edytujWskaznikiPrzycisk().click()
        e224.vatWKosztachPoleTekstowe().clear().type('10')
        e224.zapiszPrzycisk().click()
        fWspolne.sprawdzProgressBar()
        // Liczba odcinków 
        e22.liczbaOdcinkowPoleTekstowe().should('have.attr', 'value', 10)
        // Kwoty cyklu
        e22.cenaSprzedazySumarycznaPoleTekstowe().should('have.attr', 'value', '86237,70')
        e22.wartoscPrawNabytychPoleTekstowe().should('have.attr', 'value', '1000,00')
        e22.przeniesieniePrawMajatkowychLista().find('option[selected]').contains('Wartość praw nie podlega amortyzacji')
        e22.wartoscMaterialowArchiwalnychPoleTekstowe().should('have.attr', 'value', '1000,00')
        e22.wynagrodzeniePracowniczePoleTekstowe().should('have.attr', 'value', '500,00')
        e22.wynagrodzenieWspolpracowniczePoleTekstowe().should('have.attr', 'value', '23000,00')
        e22.wartFinansZInJednPoleTekstowe().should('have.attr', 'value', '1000,00')
        // Zestawienie zbiorcze kosztów jednostki TVP S.A.
        e22.pochodneOdWynagrodzenPoleTekstowe().should('have.attr', 'value', '47,50')
        e22.kosztyZewnetrznePoleTekstowe().should('have.attr', 'value', '3970,00')
        e22.kosztyBezposredniePoleTekstowe().should('have.attr', 'value', '7940,00')
        e22.kosztyPosredniePoleTekstowe().should('have.attr', 'value', '783,77')
        e22.kosztyRazemPoleTekstowe().should('have.attr', 'value', '8723,77')
        e22.kosztCalkNettoPoleTekstowe().should('have.attr', 'value', '9723,77')
        e22.vatPoleTekstowe().should('have.attr', 'value', '0,00')
        e22.vatOdPrawPoleTekstowe().should('have.attr', 'value', '2,30')
        e22.cenaSprzedazyPoleTekstowe().should('have.attr', 'value', '8623,77')
        // Wskaźniki
        e22.edytujWskaznikiPrzycisk().click()
        e224.jednostkaRozliczeniowaPoleTekstowe().siblings('input.form-control').should('have.attr', 'value', 'Jedn.Koszt.TVP')
        e224.narzutKosztowPosrPoleTekstowe().should('have.prop', 'value', '10,00 %')
        e224.vatPZPoleTekstowe().should('have.attr', 'value', '0,00')
        e224.vatWKosztachPoleTekstowe().should('have.prop', 'value', '10,00 %')
        e224.zusOdWynagrodzenPoleTekstowe().should('have.prop', 'value', '19,00 %')
        e224.sredniaOdWynagrodzenPoleTekstowe().should('have.attr', 'value', '0,00')
        e224.vatOdPrawPoleTekstowe().should('have.prop', 'value', '23,00 %')
        e224.powrotPrzycisk().click()

        cy.log('Krok 11 - Przywracam początkową wartość vatu w kosztach i weryfikuję dane porozumienia')
        e22.edytujWskaznikiPrzycisk().click()
        e224.vatWKosztachPoleTekstowe().clear().type('69,74')
        e224.zapiszPrzycisk().click()
        fWspolne.sprawdzProgressBar()
        // Liczba odcinków
        e22.liczbaOdcinkowPoleTekstowe().should('have.attr', 'value', 10)
        // Kwoty cyklu
        e22.cenaSprzedazySumarycznaPoleTekstowe().should('have.attr', 'value', '93781,07')
        e22.wartoscPrawNabytychPoleTekstowe().should('have.attr', 'value', '1000,00')
        e22.przeniesieniePrawMajatkowychLista().find('option[selected]').contains('Wartość praw nie podlega amortyzacji')
        e22.wartoscMaterialowArchiwalnychPoleTekstowe().should('have.attr', 'value', '1000,00')
        e22.wynagrodzeniePracowniczePoleTekstowe().should('have.attr', 'value', '500,00')
        e22.wynagrodzenieWspolpracowniczePoleTekstowe().should('have.attr', 'value', '23000,00')
        e22.wartFinansZInJednPoleTekstowe().should('have.attr', 'value', '1000,00')
        // Zestawienie zbiorcze kosztów jednostki TVP S.A.
        e22.pochodneOdWynagrodzenPoleTekstowe().should('have.attr', 'value', '47,50')
        e22.kosztyZewnetrznePoleTekstowe().should('have.attr', 'value', '4313,50')
        e22.kosztyBezposredniePoleTekstowe().should('have.attr', 'value', '8627,00')
        e22.kosztyPosredniePoleTekstowe().should('have.attr', 'value', '851,10')
        e22.kosztyRazemPoleTekstowe().should('have.attr', 'value', '9478,10')
        e22.kosztCalkNettoPoleTekstowe().should('have.attr', 'value', '10478,10')
        e22.vatPoleTekstowe().should('have.attr', 'value', '0,00')
        e22.vatOdPrawPoleTekstowe().should('have.attr', 'value', '16,04')
        e22.cenaSprzedazyPoleTekstowe().should('have.attr', 'value', '9378,10')
        // Wskaźniki
        e22.edytujWskaznikiPrzycisk().click()
        e224.jednostkaRozliczeniowaPoleTekstowe().siblings('input.form-control').should('have.attr', 'value', 'Jedn.Koszt.TVP')
        e224.narzutKosztowPosrPoleTekstowe().should('have.prop', 'value', '10,00 %')
        e224.vatPZPoleTekstowe().should('have.attr', 'value', '0,00')
        e224.vatWKosztachPoleTekstowe().should('have.prop', 'value', '69,74 %')
        e224.zusOdWynagrodzenPoleTekstowe().should('have.prop', 'value', '19,00 %')
        e224.sredniaOdWynagrodzenPoleTekstowe().should('have.attr', 'value', '0,00')
        e224.vatOdPrawPoleTekstowe().should('have.prop', 'value', '23,00 %')
        e224.powrotPrzycisk().click()

        cy.log('Krok 12 - Przywracam początkową liczbę odcinków i weryfikuję dane porozumienia')
        e22.liczbaOdcinkowPoleTekstowe().clear().type('1')
        e22.zapiszPrzycisk().click()
        e22.potwierdzLiczbeOdcinkowPopupPrzycisk().click()
        fWspolne.sprawdzProgressBar()
        // Liczba odcinków
        e22.liczbaOdcinkowPoleTekstowe().should('have.attr', 'value', 1)
        // Kwoty cyklu
        e22.cenaSprzedazySumarycznaPoleTekstowe().should('have.attr', 'value', '31349,62')
        e22.wartoscPrawNabytychPoleTekstowe().should('have.attr', 'value', '1000,00')
        e22.przeniesieniePrawMajatkowychLista().find('option[selected]').contains('Wartość praw nie podlega amortyzacji')
        e22.wartoscMaterialowArchiwalnychPoleTekstowe().should('have.attr', 'value', '1000,00')
        e22.wynagrodzeniePracowniczePoleTekstowe().should('have.attr', 'value', '500,00')
        e22.wynagrodzenieWspolpracowniczePoleTekstowe().should('have.attr', 'value', '23000,00')
        e22.wartFinansZInJednPoleTekstowe().should('have.attr', 'value', '1000,00')
        // Zestawienie zbiorcze kosztów jednostki TVP S.A.
        e22.pochodneOdWynagrodzenPoleTekstowe().should('have.attr', 'value', '47,50')
        e22.kosztyZewnetrznePoleTekstowe().should('have.attr', 'value', '14757,12')
        e22.kosztyBezposredniePoleTekstowe().should('have.attr', 'value', '29514,24')
        e22.kosztyPosredniePoleTekstowe().should('have.attr', 'value', '2835,38')
        e22.kosztyRazemPoleTekstowe().should('have.attr', 'value', '32349,62')
        e22.kosztCalkNettoPoleTekstowe().should('have.attr', 'value', '33349,62')
        e22.vatPoleTekstowe().should('have.attr', 'value', '0,00')
        e22.vatOdPrawPoleTekstowe().should('have.attr', 'value', '160,40')
        e22.cenaSprzedazyPoleTekstowe().should('have.attr', 'value', '31349,62')
        // Wskaźniki
        e22.edytujWskaznikiPrzycisk().click()
        e224.jednostkaRozliczeniowaPoleTekstowe().siblings('input.form-control').should('have.attr', 'value', 'Jedn.Koszt.TVP')
        e224.narzutKosztowPosrPoleTekstowe().should('have.prop', 'value', '10,00 %')
        e224.vatPZPoleTekstowe().should('have.attr', 'value', '0,00')
        e224.vatWKosztachPoleTekstowe().should('have.prop', 'value', '69,74 %')
        e224.zusOdWynagrodzenPoleTekstowe().should('have.prop', 'value', '19,00 %')
        e224.sredniaOdWynagrodzenPoleTekstowe().should('have.attr', 'value', '0,00')
        e224.vatOdPrawPoleTekstowe().should('have.prop', 'value', '23,00 %')
        e224.powrotPrzycisk().click()

        cy.log('Krok 13 - Przywracam początkową wartość narzutu kosztów pośrednich i weryfikuję dane porozumienia')
        e22.edytujWskaznikiPrzycisk().click()
        e224.narzutKosztowPosrPoleTekstowe().clear().type('0')
        e224.zapiszPrzycisk().click()
        fWspolne.sprawdzProgressBar()
        // Liczba odcinków
        e22.liczbaOdcinkowPoleTekstowe().should('have.attr', 'value', 1)
        // Kwoty cyklu
        e22.cenaSprzedazySumarycznaPoleTekstowe().should('have.attr', 'value', '28514,24')
        e22.wartoscPrawNabytychPoleTekstowe().should('have.attr', 'value', '1000,00')
        e22.przeniesieniePrawMajatkowychLista().find('option[selected]').contains('Wartość praw nie podlega amortyzacji')
        e22.wartoscMaterialowArchiwalnychPoleTekstowe().should('have.attr', 'value', '1000,00')
        e22.wynagrodzeniePracowniczePoleTekstowe().should('have.attr', 'value', '500,00')
        e22.wynagrodzenieWspolpracowniczePoleTekstowe().should('have.attr', 'value', '23000,00')
        e22.wartFinansZInJednPoleTekstowe().should('have.attr', 'value', '1000,00')
        // Zestawienie zbiorcze kosztów jednostki TVP S.A.
        e22.pochodneOdWynagrodzenPoleTekstowe().should('have.attr', 'value', '47,50')
        e22.kosztyZewnetrznePoleTekstowe().should('have.attr', 'value', '14757,12')
        e22.kosztyBezposredniePoleTekstowe().should('have.attr', 'value', '29514,24')
        e22.kosztyPosredniePoleTekstowe().should('have.attr', 'value', '0,00')
        e22.kosztyRazemPoleTekstowe().should('have.attr', 'value', '29514,24')
        e22.kosztCalkNettoPoleTekstowe().should('have.attr', 'value', '30514,24')
        e22.vatPoleTekstowe().should('have.attr', 'value', '0,00')
        e22.vatOdPrawPoleTekstowe().should('have.attr', 'value', '160,40')
        e22.cenaSprzedazyPoleTekstowe().should('have.attr', 'value', '28514,24')
        // Wskaźniki
        e22.edytujWskaznikiPrzycisk().click()
        e224.jednostkaRozliczeniowaPoleTekstowe().siblings('input.form-control').should('have.attr', 'value', 'Jedn.Koszt.TVP')
        e224.narzutKosztowPosrPoleTekstowe().should('have.attr', 'value', '0,00')
        e224.vatPZPoleTekstowe().should('have.attr', 'value', '0,00')
        e224.vatWKosztachPoleTekstowe().should('have.prop', 'value', '69,74 %')
        e224.zusOdWynagrodzenPoleTekstowe().should('have.prop', 'value', '19,00 %')
        e224.sredniaOdWynagrodzenPoleTekstowe().should('have.attr', 'value', '0,00')
        e224.vatOdPrawPoleTekstowe().should('have.prop', 'value', '23,00 %')
        e224.powrotPrzycisk().click()

        cy.log('Krok 14 - Przywracam domyślną wartość w polu Przeniesienie praw majątkowych i weryfikuję dane porozumienia')
        e22.przeniesieniePrawMajatkowychLista().select('Wartość praw podlega amortyzacji', {force: true})
        e22.zapiszPrzycisk().click()
        fWspolne.sprawdzProgressBar()
        // Liczba odcinków
        e22.liczbaOdcinkowPoleTekstowe().should('have.attr', 'value', 1)
        // Kwoty cyklu
        e22.cenaSprzedazySumarycznaPoleTekstowe().should('have.attr', 'value', '27353,84')
        e22.wartoscPrawNabytychPoleTekstowe().should('have.attr', 'value', '1000,00')
        e22.przeniesieniePrawMajatkowychLista().find('option[selected]').contains('Wartość praw podlega amortyzacji')
        e22.wartoscMaterialowArchiwalnychPoleTekstowe().should('have.attr', 'value', '1000,00')
        e22.wynagrodzeniePracowniczePoleTekstowe().should('have.attr', 'value', '500,00')
        e22.wynagrodzenieWspolpracowniczePoleTekstowe().should('have.attr', 'value', '23000,00')
        e22.wartFinansZInJednPoleTekstowe().should('have.attr', 'value', '1000,00')
        // Zestawienie zbiorcze kosztów jednostki TVP S.A.
        e22.pochodneOdWynagrodzenPoleTekstowe().should('have.attr', 'value', '47,50')
        e22.kosztyZewnetrznePoleTekstowe().should('have.attr', 'value', '14757,12')
        e22.kosztyBezposredniePoleTekstowe().should('have.attr', 'value', '29514,24')
        e22.kosztyPosredniePoleTekstowe().should('have.attr', 'value', '0,00')
        e22.kosztyRazemPoleTekstowe().should('have.attr', 'value', '29514,24')
        e22.kosztCalkNettoPoleTekstowe().should('have.attr', 'value', '30514,24')
        e22.vatPoleTekstowe().should('have.attr', 'value', '0,00')
        e22.vatOdPrawPoleTekstowe().should('have.attr', 'value', '160,40')
        e22.cenaSprzedazyPoleTekstowe().should('have.attr', 'value', '27353,84')
        // Wskaźniki
        e22.edytujWskaznikiPrzycisk().click()
        e224.jednostkaRozliczeniowaPoleTekstowe().siblings('input.form-control').should('have.attr', 'value', 'Jedn.Koszt.TVP')
        e224.narzutKosztowPosrPoleTekstowe().should('have.attr', 'value', '0,00')
        e224.vatPZPoleTekstowe().should('have.attr', 'value', '0,00')
        e224.vatWKosztachPoleTekstowe().should('have.prop', 'value', '69,74 %')
        e224.zusOdWynagrodzenPoleTekstowe().should('have.prop', 'value', '19,00 %')
        e224.sredniaOdWynagrodzenPoleTekstowe().should('have.attr', 'value', '0,00')
        e224.vatOdPrawPoleTekstowe().should('have.prop', 'value', '23,00 %')
        e224.powrotPrzycisk().click()

        cy.log('Krok 15 - Przywracam domyślną wartość finansowania z innych jednostek i weryfikuję dane porozumienia')
        e22.wartFinansZInJednPoleTekstowe().clear().type('0')
        e22.zapiszPrzycisk().click()
        fWspolne.sprawdzProgressBar()
        // Liczba odcinków
        e22.liczbaOdcinkowPoleTekstowe().should('have.attr', 'value', 1)
        // Kwoty cyklu
        e22.cenaSprzedazySumarycznaPoleTekstowe().should('have.attr', 'value', '28353,84')
        e22.wartoscPrawNabytychPoleTekstowe().should('have.attr', 'value', '1000,00')
        e22.przeniesieniePrawMajatkowychLista().find('option[selected]').contains('Wartość praw podlega amortyzacji')
        e22.wartoscMaterialowArchiwalnychPoleTekstowe().should('have.attr', 'value', '1000,00')
        e22.wynagrodzeniePracowniczePoleTekstowe().should('have.attr', 'value', '500,00')
        e22.wynagrodzenieWspolpracowniczePoleTekstowe().should('have.attr', 'value', '23000,00')
        e22.wartFinansZInJednPoleTekstowe().should('have.attr', 'value', '0,00')
        // Zestawienie zbiorcze kosztów jednostki TVP S.A.
        e22.pochodneOdWynagrodzenPoleTekstowe().should('have.attr', 'value', '47,50')
        e22.kosztyZewnetrznePoleTekstowe().should('have.attr', 'value', '14757,12')
        e22.kosztyBezposredniePoleTekstowe().should('have.attr', 'value', '29514,24')
        e22.kosztyPosredniePoleTekstowe().should('have.attr', 'value', '0,00')
        e22.kosztyRazemPoleTekstowe().should('have.attr', 'value', '29514,24')
        e22.kosztCalkNettoPoleTekstowe().should('have.attr', 'value', '30514,24')
        e22.vatPoleTekstowe().should('have.attr', 'value', '0,00')
        e22.vatOdPrawPoleTekstowe().should('have.attr', 'value', '160,40')
        e22.cenaSprzedazyPoleTekstowe().should('have.attr', 'value', '28353,84')
        // Wskaźniki
        e22.edytujWskaznikiPrzycisk().click()
        e224.jednostkaRozliczeniowaPoleTekstowe().siblings('input.form-control').should('have.attr', 'value', 'Jedn.Koszt.TVP')
        e224.narzutKosztowPosrPoleTekstowe().should('have.attr', 'value', '0,00')
        e224.vatPZPoleTekstowe().should('have.attr', 'value', '0,00')
        e224.vatWKosztachPoleTekstowe().should('have.prop', 'value', '69,74 %')
        e224.zusOdWynagrodzenPoleTekstowe().should('have.prop', 'value', '19,00 %')
        e224.sredniaOdWynagrodzenPoleTekstowe().should('have.attr', 'value', '0,00')
        e224.vatOdPrawPoleTekstowe().should('have.prop', 'value', '23,00 %')
        e224.powrotPrzycisk().click()

        cy.log('Krok 16 - Przywracam domyślną wartość praw mat. arch. i weryfikuję dane porozumienia')
        e22.wartoscMaterialowArchiwalnychPoleTekstowe().clear().type('0')
        e22.zapiszPrzycisk().click()
        fWspolne.sprawdzProgressBar()
        // Liczba odcinków
        e22.liczbaOdcinkowPoleTekstowe().should('have.attr', 'value', 1)
        // Kwoty cyklu
        e22.cenaSprzedazySumarycznaPoleTekstowe().should('have.attr', 'value', '28353,84')
        e22.wartoscPrawNabytychPoleTekstowe().should('have.attr', 'value', '1000,00')
        e22.przeniesieniePrawMajatkowychLista().find('option[selected]').contains('Wartość praw podlega amortyzacji')
        e22.wartoscMaterialowArchiwalnychPoleTekstowe().should('have.attr', 'value', '0,00')
        e22.wynagrodzeniePracowniczePoleTekstowe().should('have.attr', 'value', '500,00')
        e22.wynagrodzenieWspolpracowniczePoleTekstowe().should('have.attr', 'value', '23000,00')
        e22.wartFinansZInJednPoleTekstowe().should('have.attr', 'value', '0,00')
        // Zestawienie zbiorcze kosztów jednostki TVP S.A.
        e22.pochodneOdWynagrodzenPoleTekstowe().should('have.attr', 'value', '47,50')
        e22.kosztyZewnetrznePoleTekstowe().should('have.attr', 'value', '14757,12')
        e22.kosztyBezposredniePoleTekstowe().should('have.attr', 'value', '29514,24')
        e22.kosztyPosredniePoleTekstowe().should('have.attr', 'value', '0,00')
        e22.kosztyRazemPoleTekstowe().should('have.attr', 'value', '29514,24')
        e22.kosztCalkNettoPoleTekstowe().should('have.attr', 'value', '29514,24')
        e22.vatPoleTekstowe().should('have.attr', 'value', '0,00')
        e22.vatOdPrawPoleTekstowe().should('have.attr', 'value', '160,40')
        e22.cenaSprzedazyPoleTekstowe().should('have.attr', 'value', '28353,84')
        // Wskaźniki
        e22.edytujWskaznikiPrzycisk().click()
        e224.jednostkaRozliczeniowaPoleTekstowe().siblings('input.form-control').should('have.attr', 'value', 'Jedn.Koszt.TVP')
        e224.narzutKosztowPosrPoleTekstowe().should('have.attr', 'value', '0,00')
        e224.vatPZPoleTekstowe().should('have.attr', 'value', '0,00')
        e224.vatWKosztachPoleTekstowe().should('have.prop', 'value', '69,74 %')
        e224.zusOdWynagrodzenPoleTekstowe().should('have.prop', 'value', '19,00 %')
        e224.sredniaOdWynagrodzenPoleTekstowe().should('have.attr', 'value', '0,00')
        e224.vatOdPrawPoleTekstowe().should('have.prop', 'value', '23,00 %')
        e224.powrotPrzycisk().click()

        cy.log('Krok 17 - Przywracam domyślną wartość praw nabytych i weryfikuję dane porozumienia')
        e22.wartoscPrawNabytychPoleTekstowe().clear().type('0')
        e22.zapiszPrzycisk().click()
        fWspolne.sprawdzProgressBar()
        // Liczba odcinków
        e22.liczbaOdcinkowPoleTekstowe().should('have.attr', 'value', 1)
        // Kwoty cyklu
        e22.cenaSprzedazySumarycznaPoleTekstowe().should('have.attr', 'value', '29514,24')
        e22.wartoscPrawNabytychPoleTekstowe().should('have.attr', 'value', '0,00')
        e22.przeniesieniePrawMajatkowychLista().find('option[selected]').contains('Wartość praw podlega amortyzacji')
        e22.wartoscMaterialowArchiwalnychPoleTekstowe().should('have.attr', 'value', '0,00')
        e22.wynagrodzeniePracowniczePoleTekstowe().should('have.attr', 'value', '500,00')
        e22.wynagrodzenieWspolpracowniczePoleTekstowe().should('have.attr', 'value', '23000,00')
        e22.wartFinansZInJednPoleTekstowe().should('have.attr', 'value', '0,00')
        // Zestawienie zbiorcze kosztów jednostki TVP S.A.
        e22.pochodneOdWynagrodzenPoleTekstowe().should('have.attr', 'value', '47,50')
        e22.kosztyZewnetrznePoleTekstowe().should('have.attr', 'value', '14757,12')
        e22.kosztyBezposredniePoleTekstowe().should('have.attr', 'value', '29514,24')
        e22.kosztyPosredniePoleTekstowe().should('have.attr', 'value', '0,00')
        e22.kosztyRazemPoleTekstowe().should('have.attr', 'value', '29514,24')
        e22.kosztCalkNettoPoleTekstowe().should('have.attr', 'value', '29514,24')
        e22.vatPoleTekstowe().should('have.attr', 'value', '0,00')
        e22.vatOdPrawPoleTekstowe().should('have.attr', 'value', '0,00')
        e22.cenaSprzedazyPoleTekstowe().should('have.attr', 'value', '29514,24')
        // Wskaźniki
        e22.edytujWskaznikiPrzycisk().click()
        e224.jednostkaRozliczeniowaPoleTekstowe().siblings('input.form-control').should('have.attr', 'value', 'Jedn.Koszt.TVP')
        e224.narzutKosztowPosrPoleTekstowe().should('have.attr', 'value', '0,00')
        e224.vatPZPoleTekstowe().should('have.attr', 'value', '0,00')
        e224.vatWKosztachPoleTekstowe().should('have.prop', 'value', '69,74 %')
        e224.zusOdWynagrodzenPoleTekstowe().should('have.prop', 'value', '19,00 %')
        e224.sredniaOdWynagrodzenPoleTekstowe().should('have.attr', 'value', '0,00')
        e224.vatOdPrawPoleTekstowe().should('have.prop', 'value', '23,00 %')
        e224.powrotPrzycisk().click()

        // Wylogowanie
        cy.logoutUser()
    })
})