import { fWspolne } from '../../../../POM/Funkcje wspolne/Funkcje wspolne'
import { e20 } from '../../../../POM/Planowanie/E20 Porozumienia'
import { e22 } from '../../../../POM/Planowanie/E22 Porozumienia - szczegoly'
import { e23 } from '../../../../POM/Planowanie/E23 Koszty planowane'

describe('SEPP-17805 Weryfikacja wyświetlania kosztów powiązanych', () => {
    it('Weryfikacja wyświetlania kosztów powiązanych', () => {
        cy.log('Krok 1 - Loguję się jako Producent')
        cy.visit('/')
            .loginProducent()

        cy.log('Krok 2 - Jestem na ekranie listy porozumień i przechodzę na ekran edycji wybranego porozumienia')
        cy.goToMenu('Porozumienia')
        e20.numerPorozumieniaPoleTekstowe().type('P/1001787/AKFiS/2022')
        e20.wyszukajPrzycisk().click()
        fWspolne.sprawdzProgressBar()
        e20.edycjaPierwszyPrzycisk().click()
        fWspolne.sprawdzProgressBar()
        e22.wynagrodzenieWspolpracowniczePoleTekstowe().should('have.attr', 'value', '150,00')
        e22.cenaSprzedazyPoleTekstowe().should('have.attr', 'value', '4474,06')
        e22.cenaSprzedazySumarycznaPoleTekstowe().should('have.attr', 'value', '4474,06')
        e22.kosztyBezposredniePoleTekstowe().should('have.attr', 'value', '4474,06')
        e22.kosztyRazemPoleTekstowe().should('have.attr', 'value', '4474,06')
        e22.kosztCalkNettoPoleTekstowe().should('have.attr', 'value', '4474,06')

        cy.log('Krok 3 - Jestem na ekranie kosztów planowanych i weryfikuję zdefiniowane koszty')
        e22.kosztyPlanowanePrzycisk().click()
        e23.pokazPozycjeRadio().click()
        e23.rodzajKosztuPrzycisk('Prace literackie').should('not.exist')
        e23.rodzajKosztuPrzycisk('Prace reżysersko-realizacyjne').click()
        e23.dodajUslugeProduktPrzycisk().should('be.visible') 
        cy.get('div#costTable_102') .should('have.prop', 'childElementCount', 1)
        cy.get('.connectedTitleType').should('have.prop', 'innerText', '')
        e23.edytujKosztPrzycisk('Reżyser').click()
        e23.sumaKosztu1OdcPoleTekstowe().should('have.value', '150,00 zł')
        e23.rodzajKosztuPrzycisk('Prace reżysersko-realizacyjne').click()
        
        e23.rodzajKosztuPoz1Przycisk('KOSZTY TECHNICZNE').click()
        e23.rodzajKosztuPrzycisk('Koszty urządzeń technicznych własnych').click()
        e23.dodajUslugeProduktPrzycisk().should('be.visible')
        cy.get('div#costTable_119') .should('have.prop', 'childElementCount', 1)
        cy.get('.connectedTitleType').should('have.prop', 'innerText', '')
        e23.edytujKosztPrzycisk('STUDIO DUŻE - ≥450 m2').click()
        e23.sumaKosztu1OdcPoleTekstowe().should('have.value', '4 300,00 zł')
        e23.anulujZmianePrzycisk().click()
        e23.anulujZmianePrzycisk().should('not.exist')

        cy.log('Krok 4 - Powracam na ekranie szczegółów porozumienia i dodaję 2 kosztorysy powiązane')
        e23.powrotPrzycisk().click()
        e22.dodajKosztorysPowiazanyPrzycisk().click()
        e22.kosztorysPowiazanyPopupLista().select('P/1001788/AKFiS/2022, SEPP-17805DEV (PU)', {force: true})
        e22.potwierdzKosztorysPowiazanyPopupPrzycisk().click()
        fWspolne.sprawdzProgressBar()
        cy.get('#ConnectedTitleList > tbody > tr > td:nth-child(2)').should('contain.text', 'development')
        cy.get('#ConnectedTitleList > tbody > tr > td:nth-child(4)').should('contain.text', 'SEPP-17805DEV')
        e22.dodajKosztorysPowiazanyPrzycisk().click()
        e22.kosztorysPowiazanyPopupLista().select('P/1001789/AKFiS/2022, SEPP-17805PRACE (PU)', {force: true})
        e22.potwierdzKosztorysPowiazanyPopupPrzycisk().click()
        fWspolne.sprawdzProgressBar()
        cy.get('#ConnectedTitleList > tbody > tr:nth-child(2) > td:nth-child(2)').should('contain.text', 'prace przygotowawcze')
        cy.get('#ConnectedTitleList > tbody > tr:nth-child(2) > td:nth-child(4)').should('contain.text', 'SEPP-17805PRACE')

        cy.log('Krok 5 - Weryfikuję poprawność wartości kwotowych na porozumieniu')
        e22.wynagrodzenieWspolpracowniczePoleTekstowe().should('have.attr', 'value', '1980,00')
        e22.cenaSprzedazyPoleTekstowe().should('have.attr', 'value', '8237,59')
        e22.cenaSprzedazySumarycznaPoleTekstowe().should('have.attr', 'value', '8237,59')
        e22.kosztyBezposredniePoleTekstowe().should('have.attr', 'value', '8237,59')
        e22.kosztyRazemPoleTekstowe().should('have.attr', 'value', '8237,59')
        e22.kosztCalkNettoPoleTekstowe().should('have.attr', 'value', '8237,59')

        cy.log('Krok 6 - Jestem na ekranie kosztów planowanych i weryfikuję zdefiniowane i powiązane koszty')
        e22.kosztyPlanowanePrzycisk().click()
        e23.pokazPozycjeRadio().click()
        e23.rodzajKosztuPrzycisk('Prace literackie').should('not.exist')
        e23.rodzajKosztuPrzycisk('Prace reżysersko-realizacyjne').click()
        e23.dodajUslugeProduktPrzycisk().should('be.visible') 
        cy.get('div#costTable_102') .should('have.prop', 'childElementCount', 2)
        e23.edytujKosztPrzycisk('Reżyser').click()
        e23.sumaKosztu1OdcPoleTekstowe().should('have.value', '150,00 zł')
        cy.get('.connectedTitleType').contains('prace przygotowawcze').siblings('label').should('contain.text', 'Montażysta')
        cy.get('input[value="Montażysta"]').siblings('div.secondCostRow').find('[title="Suma kosztu usługi/produktu dla 1 odc."]').should('have.value', '880,00 zł')
        e23.rodzajKosztuPrzycisk('Prace reżysersko-realizacyjne').click()
        e23.rodzajKosztuPrzycisk('Prace techniczne i pomocnicze').click()
        e23.dodajUslugeProduktPrzycisk().should('be.visible')
        cy.get('div#costTable_106') .should('have.prop', 'childElementCount', 1)
        cy.get('.connectedTitleType').contains('development').siblings('label').should('contain.text', 'KTA - inżynier studia')
        cy.get('input[value="KTA - inżynier studia"]').siblings('div.secondCostRow').find('[title="Suma kosztu usługi/produktu dla 1 odc."]').should('have.value', '950,00 zł')
        e23.rodzajKosztuPrzycisk('Prace techniczne i pomocnicze').click()

        e23.rodzajKosztuPoz1Przycisk('KOSZTY TECHNICZNE').click()
        e23.rodzajKosztuPrzycisk('Koszty urządzeń technicznych własnych').click()
        e23.dodajUslugeProduktPrzycisk().should('be.visible')
        cy.get('div#costTable_119') .should('have.prop', 'childElementCount', 3)
        e23.edytujKosztPrzycisk('STUDIO DUŻE - ≥450 m2').click()
        e23.sumaKosztu1OdcPoleTekstowe().should('have.value', '4 300,00 zł')
        cy.get('.connectedTitleType').contains('development').siblings('label').should('contain.text', 'MONITORY')
        cy.get('input[value="MONITORY"]').siblings('div.secondCostRow').find('[title="Suma kosztu usługi/produktu dla 1 odc."]').should('have.value', '200,00 zł')
        cy.get('.connectedTitleType').contains('prace przygotowawcze').siblings('label').should('contain.text', 'MIKROPORTY - 8 torów')
        cy.get('input[value="MIKROPORTY - 8 torów"]').siblings('div.secondCostRow').find('[title="Suma kosztu usługi/produktu dla 1 odc."]').should('have.value', '1 440,00 zł')
        e23.anulujZmianePrzycisk().click()
        e23.rodzajKosztuPrzycisk('Koszty urządzeń technicznych własnych').click()

        cy.log('Krok 7 - Powracam na ekranie szczegółów porozumienia i usuwam kosztorysy powiązane')
        e23.powrotPrzycisk().click()
        e22.usunKosztorysPowiazanyPierwszyPrzycisk().click()
        e22.takUsunKosztorysPowiazanyPopupPrzycisk().click()
        fWspolne.sprawdzProgressBar()
        e22.usunKosztorysPowiazanyPierwszyPrzycisk().click()
        e22.takUsunKosztorysPowiazanyPopupPrzycisk().click()
        fWspolne.sprawdzProgressBar()

        // Wylogowanie
        cy.logoutUser()
    })
})