import { fWspolne } from '../../../../POM/Funkcje wspolne/Funkcje wspolne'
import { e23 } from '../../../../POM/Planowanie/E23 Koszty planowane'
import { e25 } from '../../../../POM/Planowanie/E25 Kosztorysy'

describe('SEPP-16303 Walidacja edytowalnosci pozycji kosztowej w zależności od jej wykorzystania', () => {
    it('Walidacja edytowalnosci pozycji kosztowej w zależności od jej wykorzystania', () => {
        // Strona główna i logowanie
        cy.visit('/')
            .loginProducent()        

        cy.log('Krok 1 - Przejście do edycji wybranego kosztorysu')
        cy.goToMenu('Kosztorysy')
        cy.get('#TvAudition').type('SEPP-16303')
        e25.wyszukajPrzycisk().click()   
        fWspolne.sprawdzProgressBar()    
        e25.edycjaKosztorysuPierwszyPrzycisk().click()

        cy.log('Krok 2 - Próba wyczyszczenia pozycji dla kosztów usługowych')
        e23.rodzajKosztuPrzycisk('Prace reżysersko-realizacyjne').click()
        e23.wyczyscKosztPrzycisk('Montażysta').click()
        cy.wait(1000)
        cy.get('a#confirmBtn').contains('Potwierdź').click()
        cy.get('div.modal-lg>div.modal-header').should('not.be.visible')
        fWspolne.komunikat().should('contain', 'Brak możliwości wyczyszczenia pozycji kosztowej. Dla danej pozycji zarezerwowano zasoby, uniemożliwiając jej wyzerowanie')
        e23.rodzajKosztuPrzycisk('Prace reżysersko-realizacyjne').click()
        e23.rodzajKosztuPrzycisk('Prace techniczne i pomocnicze').click()
        e23.dodajUslugeProduktPrzycisk().should('be.visible')
        e23.wyczyscKosztPrzycisk('RTŚ - technik światła').click()
        cy.wait(1000)
        cy.get('a#confirmBtn').contains('Potwierdź').click()
        cy.get('div.modal-lg>div.modal-header').should('not.be.visible')
        fWspolne.komunikat().should('contain', 'Brak możliwości wyczyszczenia pozycji kosztowej. Dla danej pozycji zarezerwowano zasoby, uniemożliwiając jej wyzerowanie').click()
        fWspolne.komunikat().should('not.exist')
        e23.wyczyscKosztPrzycisk('Asystent operatora steadicam').click()
        cy.wait(1000)
        cy.get('a#confirmBtn').contains('Potwierdź').click()
        cy.get('div.modal-lg>div.modal-header').should('not.be.visible')
        fWspolne.komunikat().should('contain', 'Brak możliwości wyczyszczenia pozycji kosztowej. Dla danej pozycji zarezerwowano zasoby, uniemożliwiając jej wyzerowanie')

        cy.log('Krok 3 - Próba wyczyszczenia pozycji dla kosztów sprzętowych')
        e23.rodzajKosztuPoz1Przycisk('KOSZTY TECHNICZNE').click()
        e23.rodzajKosztuPrzycisk('Koszty urządzeń technicznych własnych').click()
        e23.wyczyscKosztPrzycisk('MONTAŻ FINAL CUT').click()
        cy.wait(1000)
        cy.get('a#confirmBtn').contains('Potwierdź').click()
        cy.get('div.modal-lg>div.modal-header').should('not.be.visible')
        fWspolne.komunikat().should('contain', 'Brak możliwości wyczyszczenia pozycji kosztowej. Dla danej pozycji zarezerwowano zasoby, uniemożliwiając jej wyzerowanie').click()
        fWspolne.komunikat().should('not.exist')
        e23.wyczyscKosztPrzycisk('STATYW KAMEROWY STEADICAM').click()
        cy.wait(1000)
        cy.get('a#confirmBtn').contains('Potwierdź').click()
        cy.get('div.modal-lg>div.modal-header').should('not.be.visible')
        fWspolne.komunikat().should('contain', 'Brak możliwości wyczyszczenia pozycji kosztowej. Dla danej pozycji zarezerwowano zasoby, uniemożliwiając jej wyzerowanie').click()
        fWspolne.komunikat().should('not.exist')
        e23.wyczyscKosztPrzycisk('ZESTAW OŚWIETLENIOWY').click()
        cy.wait(1000)
        cy.get('a#confirmBtn').contains('Potwierdź').click()
        cy.get('div.modal-lg>div.modal-header').should('not.be.visible')
        fWspolne.komunikat().should('contain', 'Brak możliwości wyczyszczenia pozycji kosztowej. Dla danej pozycji zarezerwowano zasoby, uniemożliwiając jej wyzerowanie').click()
        fWspolne.komunikat().should('not.exist')

        cy.log('Krok 4 - Próba edycji jednostek obliczeniowych na pozycjach dla kosztów sprzętowych')
        e23.edytujKosztPrzycisk('MONTAŻ FINAL CUT').click()
        e23.liczbaJednObliczPoleTekstowe().clear().type('15,5')
        e23.zatwierdzKosztPrzycisk().click()
        fWspolne.komunikat().should('contain', 'Złożono rezerwacje na zasoby w liczbie przekraczającej wartości podane w polach "liczba jednostek obliczeniowych" oraz "liczba osób/sztuk". Zmodyfikuj wprowadzone wartości lub anuluj rezerwacje zasobów.').click()
        fWspolne.komunikat().should('not.exist')
        e23.anulujZmianePrzycisk().click()
        e23.edytujKosztPrzycisk('STATYW KAMEROWY STEADICAM').click()
        e23.liczbaJednObliczPoleTekstowe().clear().type('7,5')
        e23.zatwierdzKosztPrzycisk().click()
        fWspolne.komunikat().should('contain', 'Złożono rezerwacje na zasoby w liczbie przekraczającej wartości podane w polach "liczba jednostek obliczeniowych" oraz "liczba osób/sztuk". Zmodyfikuj wprowadzone wartości lub anuluj rezerwacje zasobów.').click()
        fWspolne.komunikat().should('not.exist')
        e23.anulujZmianePrzycisk().click()
        e23.edytujKosztPrzycisk('ZESTAW OŚWIETLENIOWY').click()
        e23.liczbaJednObliczPoleTekstowe().clear().type('7,5')
        e23.zatwierdzKosztPrzycisk().click()
        fWspolne.komunikat().should('contain', 'Złożono rezerwacje na zasoby w liczbie przekraczającej wartości podane w polach "liczba jednostek obliczeniowych" oraz "liczba osób/sztuk". Zmodyfikuj wprowadzone wartości lub anuluj rezerwacje zasobów.').click()
        fWspolne.komunikat().should('not.exist')
        e23.anulujZmianePrzycisk().click()

        cy.log('Krok 5 - Próba edycji jednostek obliczeniowych na pozycjach dla kosztów usługowych')
        e23.rodzajKosztuPoz1Przycisk('WYNAGRODZENIA RAZEM').click()
        e23.rodzajKosztuPrzycisk('Prace reżysersko-realizacyjne').click()
        e23.edytujKosztPrzycisk('Montażysta').click()
        e23.liczbaJednObliczPoleTekstowe().clear().type('7,5')
        e23.zatwierdzKosztPrzycisk().click()
        fWspolne.komunikat().should('contain', 'Złożono rezerwacje na zasoby w liczbie przekraczającej wartości podane w polach "liczba jednostek obliczeniowych" oraz "liczba osób/sztuk". Zmodyfikuj wprowadzone wartości lub anuluj rezerwacje zasobów.').click()
        fWspolne.komunikat().should('not.exist')
        e23.anulujZmianePrzycisk().click()
        e23.rodzajKosztuPrzycisk('Prace reżysersko-realizacyjne').click()
        e23.rodzajKosztuPrzycisk('Prace techniczne i pomocnicze').click()
        e23.dodajUslugeProduktPrzycisk().should('be.visible')
        e23.edytujKosztPrzycisk('RTŚ - technik światła').click()
        e23.liczbaJednObliczPoleTekstowe().clear().type('7,5')
        e23.zatwierdzKosztPrzycisk().click()
        fWspolne.komunikat().should('contain', 'Złożono rezerwacje na zasoby w liczbie przekraczającej wartości podane w polach "liczba jednostek obliczeniowych" oraz "liczba osób/sztuk". Zmodyfikuj wprowadzone wartości lub anuluj rezerwacje zasobów.').click()
        fWspolne.komunikat().should('not.exist')
        e23.anulujZmianePrzycisk().click()
        e23.edytujKosztPrzycisk('Asystent operatora steadicam').click()
        e23.liczbaJednObliczPoleTekstowe().clear().type('0,7')
        e23.zatwierdzKosztPrzycisk().click()
        fWspolne.komunikat().should('contain', 'Złożono rezerwacje na zasoby w liczbie przekraczającej wartości podane w polach "liczba jednostek obliczeniowych" oraz "liczba osób/sztuk". Zmodyfikuj wprowadzone wartości lub anuluj rezerwacje zasobów.').click()
        fWspolne.komunikat().should('not.exist')
        e23.anulujZmianePrzycisk().click()
        
        // Wylogowanie
        cy.log('Wylogowuje się z systemu')
        cy.logoutUser()
    })
})