import { fWspolne } from '../../../../POM/Funkcje wspolne/Funkcje wspolne'
import { e20 } from '../../../../POM/Planowanie/E20 Porozumienia'
import { e22 } from '../../../../POM/Planowanie/E22 Porozumienia - szczegoly'
import { e224 } from '../../../../POM/Planowanie/E224 Dodawanie i edycja wskaznikow'

describe('SEPP-18134 Wyliczenia dla audycji TV - PZ', () => {
    it('Wyliczenia dla audycji TV - PZ', () => {
        cy.log('Krok 1 - Loguję się jako Producent')
        cy.visit('/')
            .loginProducent()

        cy.log('Krok 2 - Jestem na ekranie listy porozumień i przechodzę na ekran edycji wybranego porozumienia')
        cy.goToMenu('Porozumienia')
        e20.nazwaAudycjiTVPoleTekstowe().type('SEPP-18134')
        e20.wyszukajPrzycisk().click()
        fWspolne.sprawdzProgressBar()
        e20.edycjaPierwszyPrzycisk().click()
        fWspolne.sprawdzProgressBar()
        
        cy.log('Krok 3 - Weryfikuję istniejące dane porozumienia')
        // Liczba odcinków
        e22.liczbaOdcinkowPoleTekstowe().should('have.attr', 'value', 1)
        // Sprzedaż zewnętrzna
        e22.kozPoleTekstowe().should('have.attr', 'value', '0,00')
        e22.kosztyOgolnegoZarzadu1OdcPoleTekstowe().should('have.attr', 'value', '0,00')
        e22.kosztyOgolnegoZarzaduCalkPoleTekstowe().should('have.attr', 'value', '0,00')
        e22.zyskPoleTekstowe().should('have.attr', 'value', '0,00')
        e22.zysk1OdcPoleTekstowe().should('have.attr', 'value', '0,00')
        e22.zyskCalkowityPoleTekstowe().should('have.attr', 'value', '0,00')
        // Kwoty cyklu
        e22.cenaSprzedazySumarycznaPoleTekstowe().should('have.attr', 'value', '29514,24')
        e22.wartoscPrawNabytychPoleTekstowe().should('have.attr', 'value', '0,00')
        e22.przeniesieniePrawMajatkowychLista().find('option[selected]').contains('Wartość praw podlega amortyzacji')
        e22.wartoscMaterialowArchiwalnychPoleTekstowe().should('have.attr', 'value', '0,00')
        e22.wynagrodzeniePracowniczePoleTekstowe().should('have.attr', 'value', '500,00')
        e22.wynagrodzenieWspolpracowniczePoleTekstowe().should('have.attr', 'value', '23000,00')
        e22.wartFinansZInJednPoleTekstowe().should('have.attr', 'value', '0,00')
        // Zestawienie zbiorcze kosztów jednostki TVP S.A.
        e22.pochodneOdWynagrodzenPoleTekstowe().should('have.attr', 'value', '47,50')
        e22.kosztyZewnetrznePoleTekstowe().should('have.attr', 'value', '14757,12')
        e22.kosztyBezposredniePoleTekstowe().should('have.attr', 'value', '29514,24')
        e22.kosztyPosredniePoleTekstowe().should('have.attr', 'value', '0,00')
        e22.kosztyRazemPoleTekstowe().should('have.attr', 'value', '29514,24')
        e22.kosztCalkNettoPoleTekstowe().should('have.attr', 'value', '29514,24')
        e22.vatPoleTekstowe().should('have.attr', 'value', '0,00')
        e22.vatOdPrawPoleTekstowe().should('have.attr', 'value', '0,00')
        e22.cenaSprzedazyPoleTekstowe().should('have.attr', 'value', '29514,24')
        // Wskaźniki
        e22.edytujWskaznikiPrzycisk().click()
        e224.jednostkaRozliczeniowaPoleTekstowe().siblings('input.form-control').should('have.attr', 'value', 'Jedn.Koszt.TVP')
        e224.narzutKosztowPosrPoleTekstowe().should('have.attr', 'value', '0,00')
        e224.vatPZPoleTekstowe().should('have.attr', 'value', '0,00')
        e224.vatWKosztachPoleTekstowe().should('have.prop', 'value', '69,74 %')
        e224.zusOdWynagrodzenPoleTekstowe().should('have.prop', 'value', '19,00 %')
        e224.sredniaOdWynagrodzenPoleTekstowe().should('have.attr', 'value', '0,00')
        e224.vatOdPrawPoleTekstowe().should('have.prop', 'value', '23,00 %')
        e224.powrotPrzycisk().click()

        cy.log('Krok 4 - Zmieniam wartość KOZ i weryfikuję dane porozumienia')
        e22.kozPoleTekstowe().clear().type('10')
        e22.zapiszPrzycisk().click()
        fWspolne.sprawdzProgressBar() 
        // Liczba odcinków
        e22.liczbaOdcinkowPoleTekstowe().should('have.attr', 'value', 1)
        // Sprzedaż zewnętrzna
        e22.kozPoleTekstowe().should('have.prop', 'value', '10,00 %')
        e22.kosztyOgolnegoZarzadu1OdcPoleTekstowe().should('have.attr', 'value', '2951,42')
        e22.kosztyOgolnegoZarzaduCalkPoleTekstowe().should('have.attr', 'value', '2951,42')
        e22.zyskPoleTekstowe().should('have.attr', 'value', '0,00')
        e22.zysk1OdcPoleTekstowe().should('have.attr', 'value', '0,00')
        e22.zyskCalkowityPoleTekstowe().should('have.attr', 'value', '0,00')
        // Kwoty cyklu
        e22.cenaSprzedazySumarycznaPoleTekstowe().should('have.attr', 'value', '32465,66')
        e22.wartoscPrawNabytychPoleTekstowe().should('have.attr', 'value', '0,00')
        e22.przeniesieniePrawMajatkowychLista().find('option[selected]').contains('Wartość praw podlega amortyzacji')
        e22.wartoscMaterialowArchiwalnychPoleTekstowe().should('have.attr', 'value', '0,00')
        e22.wynagrodzeniePracowniczePoleTekstowe().should('have.attr', 'value', '500,00')
        e22.wynagrodzenieWspolpracowniczePoleTekstowe().should('have.attr', 'value', '23000,00')
        e22.wartFinansZInJednPoleTekstowe().should('have.attr', 'value', '0,00')
        // Zestawienie zbiorcze kosztów jednostki TVP S.A.
        e22.pochodneOdWynagrodzenPoleTekstowe().should('have.attr', 'value', '47,50')
        e22.kosztyZewnetrznePoleTekstowe().should('have.attr', 'value', '14757,12')
        e22.kosztyBezposredniePoleTekstowe().should('have.attr', 'value', '29514,24')
        e22.kosztyPosredniePoleTekstowe().should('have.attr', 'value', '0,00')
        e22.kosztyRazemPoleTekstowe().should('have.attr', 'value', '32465,66')
        e22.kosztCalkNettoPoleTekstowe().should('have.attr', 'value', '32465,66')
        e22.vatPoleTekstowe().should('have.attr', 'value', '0,00')
        e22.vatOdPrawPoleTekstowe().should('have.attr', 'value', '0,00')
        e22.cenaSprzedazyPoleTekstowe().should('have.attr', 'value', '32465,66')
        // Wskaźniki
        e22.edytujWskaznikiPrzycisk().click()
        e224.jednostkaRozliczeniowaPoleTekstowe().siblings('input.form-control').should('have.attr', 'value', 'Jedn.Koszt.TVP')
        e224.narzutKosztowPosrPoleTekstowe().should('have.attr', 'value', '0,00')
        e224.vatPZPoleTekstowe().should('have.attr', 'value', '0,00')
        e224.vatWKosztachPoleTekstowe().should('have.prop', 'value', '69,74 %')
        e224.zusOdWynagrodzenPoleTekstowe().should('have.prop', 'value', '19,00 %')
        e224.sredniaOdWynagrodzenPoleTekstowe().should('have.attr', 'value', '0,00')
        e224.vatOdPrawPoleTekstowe().should('have.prop', 'value', '23,00 %')
        e224.powrotPrzycisk().click() 

        cy.log('Krok 5 - Zmieniam wartość w polu Zysk i weryfikuję dane porozumienia')
        e22.zyskPoleTekstowe().clear().type('10')
        e22.zapiszPrzycisk().click()
        fWspolne.sprawdzProgressBar() 
        // Liczba odcinków
        e22.liczbaOdcinkowPoleTekstowe().should('have.attr', 'value', 1)
        // Sprzedaż zewnętrzna
        e22.kozPoleTekstowe().should('have.prop', 'value', '10,00 %')
        e22.kosztyOgolnegoZarzadu1OdcPoleTekstowe().should('have.attr', 'value', '2951,42')
        e22.kosztyOgolnegoZarzaduCalkPoleTekstowe().should('have.attr', 'value', '2951,42')
        e22.zyskPoleTekstowe().should('have.prop', 'value', '10,00 %')
        e22.zysk1OdcPoleTekstowe().should('have.attr', 'value', '3246,57')
        e22.zyskCalkowityPoleTekstowe().should('have.attr', 'value', '3246,57')
        // Kwoty cyklu
        e22.cenaSprzedazySumarycznaPoleTekstowe().should('have.attr', 'value', '35712,23')
        e22.wartoscPrawNabytychPoleTekstowe().should('have.attr', 'value', '0,00')
        e22.przeniesieniePrawMajatkowychLista().find('option[selected]').contains('Wartość praw podlega amortyzacji')
        e22.wartoscMaterialowArchiwalnychPoleTekstowe().should('have.attr', 'value', '0,00')
        e22.wynagrodzeniePracowniczePoleTekstowe().should('have.attr', 'value', '500,00')
        e22.wynagrodzenieWspolpracowniczePoleTekstowe().should('have.attr', 'value', '23000,00')
        e22.wartFinansZInJednPoleTekstowe().should('have.attr', 'value', '0,00')
        // Zestawienie zbiorcze kosztów jednostki TVP S.A.
        e22.pochodneOdWynagrodzenPoleTekstowe().should('have.attr', 'value', '47,50')
        e22.kosztyZewnetrznePoleTekstowe().should('have.attr', 'value', '14757,12')
        e22.kosztyBezposredniePoleTekstowe().should('have.attr', 'value', '29514,24')
        e22.kosztyPosredniePoleTekstowe().should('have.attr', 'value', '0,00')
        e22.kosztyRazemPoleTekstowe().should('have.attr', 'value', '32465,66')
        e22.kosztCalkNettoPoleTekstowe().should('have.attr', 'value', '35712,23')
        e22.vatPoleTekstowe().should('have.attr', 'value', '0,00')
        e22.vatOdPrawPoleTekstowe().should('have.attr', 'value', '0,00')
        e22.cenaSprzedazyPoleTekstowe().should('have.attr', 'value', '35712,23')
        // Wskaźniki
        e22.edytujWskaznikiPrzycisk().click()
        e224.jednostkaRozliczeniowaPoleTekstowe().siblings('input.form-control').should('have.attr', 'value', 'Jedn.Koszt.TVP')
        e224.narzutKosztowPosrPoleTekstowe().should('have.attr', 'value', '0,00')
        e224.vatPZPoleTekstowe().should('have.attr', 'value', '0,00')
        e224.vatWKosztachPoleTekstowe().should('have.prop', 'value', '69,74 %')
        e224.zusOdWynagrodzenPoleTekstowe().should('have.prop', 'value', '19,00 %')
        e224.sredniaOdWynagrodzenPoleTekstowe().should('have.attr', 'value', '0,00')
        e224.vatOdPrawPoleTekstowe().should('have.prop', 'value', '23,00 %')
        e224.powrotPrzycisk().click()

        cy.log('Krok 6 - Zmieniam liczbę odcinków i weryfikuję dane porozumienia')
        e22.liczbaOdcinkowPoleTekstowe().clear().type('10')
        e22.zapiszPrzycisk().click()
        e22.potwierdzLiczbeOdcinkowPopupPrzycisk().click()
        fWspolne.sprawdzProgressBar()
        // Liczba odcinków
        e22.liczbaOdcinkowPoleTekstowe().should('have.attr', 'value', 10)
        // Sprzedaż zewnętrzna
        e22.kozPoleTekstowe().should('have.prop', 'value', '10,00 %')
        e22.kosztyOgolnegoZarzadu1OdcPoleTekstowe().should('have.attr', 'value', '862,70')
        e22.kosztyOgolnegoZarzaduCalkPoleTekstowe().should('have.attr', 'value', '8627,00')
        e22.zyskPoleTekstowe().should('have.prop', 'value', '10,00 %')
        e22.zysk1OdcPoleTekstowe().should('have.attr', 'value', '948,97')
        e22.zyskCalkowityPoleTekstowe().should('have.attr', 'value', '9489,70')
        // Kwoty cyklu
        e22.cenaSprzedazySumarycznaPoleTekstowe().should('have.attr', 'value', '104386,80')
        e22.wartoscPrawNabytychPoleTekstowe().should('have.attr', 'value', '0,00')
        e22.przeniesieniePrawMajatkowychLista().find('option[selected]').contains('Wartość praw podlega amortyzacji')
        e22.wartoscMaterialowArchiwalnychPoleTekstowe().should('have.attr', 'value', '0,00')
        e22.wynagrodzeniePracowniczePoleTekstowe().should('have.attr', 'value', '500,00')
        e22.wynagrodzenieWspolpracowniczePoleTekstowe().should('have.attr', 'value', '23000,00')
        e22.wartFinansZInJednPoleTekstowe().should('have.attr', 'value', '0,00')
        // Zestawienie zbiorcze kosztów jednostki TVP S.A.
        e22.pochodneOdWynagrodzenPoleTekstowe().should('have.attr', 'value', '47,50')
        e22.kosztyZewnetrznePoleTekstowe().should('have.attr', 'value', '4313,50')
        e22.kosztyBezposredniePoleTekstowe().should('have.attr', 'value', '8627,00')
        e22.kosztyPosredniePoleTekstowe().should('have.attr', 'value', '0,00')
        e22.kosztyRazemPoleTekstowe().should('have.attr', 'value', '9489,70')
        e22.kosztCalkNettoPoleTekstowe().should('have.attr', 'value', '10438,67')
        e22.vatPoleTekstowe().should('have.attr', 'value', '0,00')
        e22.vatOdPrawPoleTekstowe().should('have.attr', 'value', '0,00')
        e22.cenaSprzedazyPoleTekstowe().should('have.attr', 'value', '10438,67')
        // Wskaźniki
        e22.edytujWskaznikiPrzycisk().click()
        e224.jednostkaRozliczeniowaPoleTekstowe().siblings('input.form-control').should('have.attr', 'value', 'Jedn.Koszt.TVP')
        e224.narzutKosztowPosrPoleTekstowe().should('have.attr', 'value', '0,00')
        e224.vatPZPoleTekstowe().should('have.attr', 'value', '0,00')
        e224.vatWKosztachPoleTekstowe().should('have.prop', 'value', '69,74 %')
        e224.zusOdWynagrodzenPoleTekstowe().should('have.prop', 'value', '19,00 %')
        e224.sredniaOdWynagrodzenPoleTekstowe().should('have.attr', 'value', '0,00')
        e224.vatOdPrawPoleTekstowe().should('have.prop', 'value', '23,00 %')
        e224.powrotPrzycisk().click()

        cy.log('Krok 7 - Zmieniam wartość praw nabytych i weryfikuję dane porozumienia')
        e22.wartoscPrawNabytychPoleTekstowe().clear().type('1000')
        e22.zapiszPrzycisk().click()
        fWspolne.sprawdzProgressBar()
        // Liczba odcinków
        e22.liczbaOdcinkowPoleTekstowe().should('have.attr', 'value', 10)
        // Sprzedaż zewnętrzna
        e22.kozPoleTekstowe().should('have.prop', 'value', '10,00 %')
        e22.kosztyOgolnegoZarzadu1OdcPoleTekstowe().should('have.attr', 'value', '862,70')
        e22.kosztyOgolnegoZarzaduCalkPoleTekstowe().should('have.attr', 'value', '8627,00')
        e22.zyskPoleTekstowe().should('have.prop', 'value', '10,00 %')
        e22.zysk1OdcPoleTekstowe().should('have.attr', 'value', '948,97')
        e22.zyskCalkowityPoleTekstowe().should('have.attr', 'value', '9489,70')
        // Kwoty cyklu
        e22.cenaSprzedazySumarycznaPoleTekstowe().should('have.attr', 'value', '104386,80')
        e22.wartoscPrawNabytychPoleTekstowe().should('have.attr', 'value', '1000,00')
        e22.przeniesieniePrawMajatkowychLista().find('option[selected]').contains('Wartość praw podlega amortyzacji')
        e22.wartoscMaterialowArchiwalnychPoleTekstowe().should('have.attr', 'value', '0,00')
        e22.wynagrodzeniePracowniczePoleTekstowe().should('have.attr', 'value', '500,00')
        e22.wynagrodzenieWspolpracowniczePoleTekstowe().should('have.attr', 'value', '23000,00')
        e22.wartFinansZInJednPoleTekstowe().should('have.attr', 'value', '0,00')
        // Zestawienie zbiorcze kosztów jednostki TVP S.A.
        e22.pochodneOdWynagrodzenPoleTekstowe().should('have.attr', 'value', '47,50')
        e22.kosztyZewnetrznePoleTekstowe().should('have.attr', 'value', '4313,50')
        e22.kosztyBezposredniePoleTekstowe().should('have.attr', 'value', '8627,00')
        e22.kosztyPosredniePoleTekstowe().should('have.attr', 'value', '0,00')
        e22.kosztyRazemPoleTekstowe().should('have.attr', 'value', '9489,70')
        e22.kosztCalkNettoPoleTekstowe().should('have.attr', 'value', '10438,67')
        e22.vatPoleTekstowe().should('have.attr', 'value', '0,00')
        e22.vatOdPrawPoleTekstowe().should('have.attr', 'value', '16,04')
        e22.cenaSprzedazyPoleTekstowe().should('have.attr', 'value', '10438,67')
        // Wskaźniki
        e22.edytujWskaznikiPrzycisk().click()
        e224.jednostkaRozliczeniowaPoleTekstowe().siblings('input.form-control').should('have.attr', 'value', 'Jedn.Koszt.TVP')
        e224.narzutKosztowPosrPoleTekstowe().should('have.attr', 'value', '0,00')
        e224.vatPZPoleTekstowe().should('have.attr', 'value', '0,00')
        e224.vatWKosztachPoleTekstowe().should('have.prop', 'value', '69,74 %')
        e224.zusOdWynagrodzenPoleTekstowe().should('have.prop', 'value', '19,00 %')
        e224.sredniaOdWynagrodzenPoleTekstowe().should('have.attr', 'value', '0,00')
        e224.vatOdPrawPoleTekstowe().should('have.prop', 'value', '23,00 %')
        e224.powrotPrzycisk().click()

        cy.log('Krok 8 - Zmieniam wartość praw mat. arch. i weryfikuję dane porozumienia')
        e22.wartoscMaterialowArchiwalnychPoleTekstowe().clear().type('1000')
        e22.zapiszPrzycisk().click()
        fWspolne.sprawdzProgressBar()
        // Liczba odcinków 
        e22.liczbaOdcinkowPoleTekstowe().should('have.attr', 'value', 10)
        // Sprzedaż zewnętrzna
        e22.kozPoleTekstowe().should('have.prop', 'value', '10,00 %')
        e22.kosztyOgolnegoZarzadu1OdcPoleTekstowe().should('have.attr', 'value', '862,70')
        e22.kosztyOgolnegoZarzaduCalkPoleTekstowe().should('have.attr', 'value', '8627,00')
        e22.zyskPoleTekstowe().should('have.prop', 'value', '10,00 %')
        e22.zysk1OdcPoleTekstowe().should('have.attr', 'value', '948,97')
        e22.zyskCalkowityPoleTekstowe().should('have.attr', 'value', '9489,70')
        // Kwoty cyklu
        e22.cenaSprzedazySumarycznaPoleTekstowe().should('have.attr', 'value', '104386,80')
        e22.wartoscPrawNabytychPoleTekstowe().should('have.attr', 'value', '1000,00')
        e22.przeniesieniePrawMajatkowychLista().find('option[selected]').contains('Wartość praw podlega amortyzacji')
        e22.wartoscMaterialowArchiwalnychPoleTekstowe().should('have.attr', 'value', '1000,00')
        e22.wynagrodzeniePracowniczePoleTekstowe().should('have.attr', 'value', '500,00')
        e22.wynagrodzenieWspolpracowniczePoleTekstowe().should('have.attr', 'value', '23000,00')
        e22.wartFinansZInJednPoleTekstowe().should('have.attr', 'value', '0,00')
        // Zestawienie zbiorcze kosztów jednostki TVP S.A.
        e22.pochodneOdWynagrodzenPoleTekstowe().should('have.attr', 'value', '47,50')
        e22.kosztyZewnetrznePoleTekstowe().should('have.attr', 'value', '4313,50')
        e22.kosztyBezposredniePoleTekstowe().should('have.attr', 'value', '8627,00')
        e22.kosztyPosredniePoleTekstowe().should('have.attr', 'value', '0,00')
        e22.kosztyRazemPoleTekstowe().should('have.attr', 'value', '9489,70')
        e22.kosztCalkNettoPoleTekstowe().should('have.attr', 'value', '10438,67')
        e22.vatPoleTekstowe().should('have.attr', 'value', '0,00')
        e22.vatOdPrawPoleTekstowe().should('have.attr', 'value', '16,04')
        e22.cenaSprzedazyPoleTekstowe().should('have.attr', 'value', '10438,67')
        // Wskaźniki
        e22.edytujWskaznikiPrzycisk().click()
        e224.jednostkaRozliczeniowaPoleTekstowe().siblings('input.form-control').should('have.attr', 'value', 'Jedn.Koszt.TVP')
        e224.narzutKosztowPosrPoleTekstowe().should('have.attr', 'value', '0,00')
        e224.vatPZPoleTekstowe().should('have.attr', 'value', '0,00')
        e224.vatWKosztachPoleTekstowe().should('have.prop', 'value', '69,74 %')
        e224.zusOdWynagrodzenPoleTekstowe().should('have.prop', 'value', '19,00 %')
        e224.sredniaOdWynagrodzenPoleTekstowe().should('have.attr', 'value', '0,00')
        e224.vatOdPrawPoleTekstowe().should('have.prop', 'value', '23,00 %')
        e224.powrotPrzycisk().click()

        cy.log('Krok 9 - Zmieniam wartość finansowania z innych jednostek i weryfikuję dane porozumienia')
        e22.wartFinansZInJednPoleTekstowe().clear().type('1000')
        e22.zapiszPrzycisk().click()
        fWspolne.sprawdzProgressBar()
        // Liczba odcinków 
        e22.liczbaOdcinkowPoleTekstowe().should('have.attr', 'value', 10)
        // Sprzedaż zewnętrzna
        e22.kozPoleTekstowe().should('have.prop', 'value', '10,00 %')
        e22.kosztyOgolnegoZarzadu1OdcPoleTekstowe().should('have.attr', 'value', '862,70')
        e22.kosztyOgolnegoZarzaduCalkPoleTekstowe().should('have.attr', 'value', '8627,00')
        e22.zyskPoleTekstowe().should('have.prop', 'value', '10,00 %')
        e22.zysk1OdcPoleTekstowe().should('have.attr', 'value', '948,97')
        e22.zyskCalkowityPoleTekstowe().should('have.attr', 'value', '9489,70')
        // Kwoty cyklu
        e22.cenaSprzedazySumarycznaPoleTekstowe().should('have.attr', 'value', '103386,80')
        e22.wartoscPrawNabytychPoleTekstowe().should('have.attr', 'value', '1000,00')
        e22.przeniesieniePrawMajatkowychLista().find('option[selected]').contains('Wartość praw podlega amortyzacji')
        e22.wartoscMaterialowArchiwalnychPoleTekstowe().should('have.attr', 'value', '1000,00')
        e22.wynagrodzeniePracowniczePoleTekstowe().should('have.attr', 'value', '500,00')
        e22.wynagrodzenieWspolpracowniczePoleTekstowe().should('have.attr', 'value', '23000,00')
        e22.wartFinansZInJednPoleTekstowe().should('have.attr', 'value', '1000,00')
        // Zestawienie zbiorcze kosztów jednostki TVP S.A.
        e22.pochodneOdWynagrodzenPoleTekstowe().should('have.attr', 'value', '47,50')
        e22.kosztyZewnetrznePoleTekstowe().should('have.attr', 'value', '4313,50')
        e22.kosztyBezposredniePoleTekstowe().should('have.attr', 'value', '8627,00')
        e22.kosztyPosredniePoleTekstowe().should('have.attr', 'value', '0,00')
        e22.kosztyRazemPoleTekstowe().should('have.attr', 'value', '9489,70')
        e22.kosztCalkNettoPoleTekstowe().should('have.attr', 'value', '10438,67')
        e22.vatPoleTekstowe().should('have.attr', 'value', '0,00')
        e22.vatOdPrawPoleTekstowe().should('have.attr', 'value', '16,04')
        e22.cenaSprzedazyPoleTekstowe().should('have.attr', 'value', '10338,67')
        // Wskaźniki
        e22.edytujWskaznikiPrzycisk().click()
        e224.jednostkaRozliczeniowaPoleTekstowe().siblings('input.form-control').should('have.attr', 'value', 'Jedn.Koszt.TVP')
        e224.narzutKosztowPosrPoleTekstowe().should('have.attr', 'value', '0,00')
        e224.vatPZPoleTekstowe().should('have.attr', 'value', '0,00')
        e224.vatWKosztachPoleTekstowe().should('have.prop', 'value', '69,74 %')
        e224.zusOdWynagrodzenPoleTekstowe().should('have.prop', 'value', '19,00 %')
        e224.sredniaOdWynagrodzenPoleTekstowe().should('have.attr', 'value', '0,00')
        e224.vatOdPrawPoleTekstowe().should('have.prop', 'value', '23,00 %')
        e224.powrotPrzycisk().click()

        cy.log('Krok 10 - Zmieniam wartość w polu Przeniesienie praw majątkowych i weryfikuję dane porozumienia')
        e22.przeniesieniePrawMajatkowychLista().select('Wartość praw nie podlega amortyzacji', {force: true})
        cy.wait(500)
        e22.potwierdzPrzeniesieniePrawPopupPrzycisk().should('be.visible').click()
        e22.potwierdzPrzeniesieniePrawPopupPrzycisk().should('not.be.visible')
        e22.zapiszPrzycisk().click()
        fWspolne.sprawdzProgressBar()
        // Liczba odcinków 
        e22.liczbaOdcinkowPoleTekstowe().should('have.attr', 'value', 10)
        // Sprzedaż zewnętrzna
        e22.kozPoleTekstowe().should('have.prop', 'value', '10,00 %')
        e22.kosztyOgolnegoZarzadu1OdcPoleTekstowe().should('have.attr', 'value', '862,70')
        e22.kosztyOgolnegoZarzaduCalkPoleTekstowe().should('have.attr', 'value', '8627,00')
        e22.zyskPoleTekstowe().should('have.prop', 'value', '10,00 %')
        e22.zysk1OdcPoleTekstowe().should('have.attr', 'value', '948,97')
        e22.zyskCalkowityPoleTekstowe().should('have.attr', 'value', '9489,70')
        // Kwoty cyklu
        e22.cenaSprzedazySumarycznaPoleTekstowe().should('have.attr', 'value', '103386,80')
        e22.wartoscPrawNabytychPoleTekstowe().should('have.attr', 'value', '1000,00')
        e22.przeniesieniePrawMajatkowychLista().find('option[selected]').contains('Wartość praw nie podlega amortyzacji')
        e22.wartoscMaterialowArchiwalnychPoleTekstowe().should('have.attr', 'value', '1000,00')
        e22.wynagrodzeniePracowniczePoleTekstowe().should('have.attr', 'value', '500,00')
        e22.wynagrodzenieWspolpracowniczePoleTekstowe().should('have.attr', 'value', '23000,00')
        e22.wartFinansZInJednPoleTekstowe().should('have.attr', 'value', '1000,00')
        // Zestawienie zbiorcze kosztów jednostki TVP S.A.
        e22.pochodneOdWynagrodzenPoleTekstowe().should('have.attr', 'value', '47,50')
        e22.kosztyZewnetrznePoleTekstowe().should('have.attr', 'value', '4313,50')
        e22.kosztyBezposredniePoleTekstowe().should('have.attr', 'value', '8627,00')
        e22.kosztyPosredniePoleTekstowe().should('have.attr', 'value', '0,00')
        e22.kosztyRazemPoleTekstowe().should('have.attr', 'value', '9489,70')
        e22.kosztCalkNettoPoleTekstowe().should('have.attr', 'value', '10438,67')
        e22.vatPoleTekstowe().should('have.attr', 'value', '0,00')
        e22.vatOdPrawPoleTekstowe().should('have.attr', 'value', '16,04')
        e22.cenaSprzedazyPoleTekstowe().should('have.attr', 'value', '10338,67')
        // Wskaźniki
        e22.edytujWskaznikiPrzycisk().click()
        e224.jednostkaRozliczeniowaPoleTekstowe().siblings('input.form-control').should('have.attr', 'value', 'Jedn.Koszt.TVP')
        e224.narzutKosztowPosrPoleTekstowe().should('have.attr', 'value', '0,00')
        e224.vatPZPoleTekstowe().should('have.attr', 'value', '0,00')
        e224.vatWKosztachPoleTekstowe().should('have.prop', 'value', '69,74 %')
        e224.zusOdWynagrodzenPoleTekstowe().should('have.prop', 'value', '19,00 %')
        e224.sredniaOdWynagrodzenPoleTekstowe().should('have.attr', 'value', '0,00')
        e224.vatOdPrawPoleTekstowe().should('have.prop', 'value', '23,00 %')
        e224.powrotPrzycisk().click()

        cy.log('Krok 11 - Zmieniam wartość narzutu kosztów pośrednich we wskaźnikach i weryfikuję dane porozumienia')
        e22.edytujWskaznikiPrzycisk().click()
        e224.narzutKosztowPosrPoleTekstowe().clear().type('10')
        e224.zapiszPrzycisk().click()
        fWspolne.sprawdzProgressBar()
        e22.zapiszPrzycisk().click()
        fWspolne.sprawdzProgressBar()
        // Liczba odcinków 
        e22.liczbaOdcinkowPoleTekstowe().should('have.attr', 'value', 10)
        // Sprzedaż zewnętrzna
        e22.kozPoleTekstowe().should('have.prop', 'value', '10,00 %')
        e22.kosztyOgolnegoZarzadu1OdcPoleTekstowe().should('have.attr', 'value', '989,06')
        e22.kosztyOgolnegoZarzaduCalkPoleTekstowe().should('have.attr', 'value', '9890,60')
        e22.zyskPoleTekstowe().should('have.prop', 'value', '10,00 %')
        e22.zysk1OdcPoleTekstowe().should('have.attr', 'value', '1087,97')
        e22.zyskCalkowityPoleTekstowe().should('have.attr', 'value', '10879,66')
        // Kwoty cyklu
        e22.cenaSprzedazySumarycznaPoleTekstowe().should('have.attr', 'value', '118676,33')
        e22.wartoscPrawNabytychPoleTekstowe().should('have.attr', 'value', '1000,00')
        e22.przeniesieniePrawMajatkowychLista().find('option[selected]').contains('Wartość praw nie podlega amortyzacji')
        e22.wartoscMaterialowArchiwalnychPoleTekstowe().should('have.attr', 'value', '1000,00')
        e22.wynagrodzeniePracowniczePoleTekstowe().should('have.attr', 'value', '500,00')
        e22.wynagrodzenieWspolpracowniczePoleTekstowe().should('have.attr', 'value', '23000,00')
        e22.wartFinansZInJednPoleTekstowe().should('have.attr', 'value', '1000,00')
        // Zestawienie zbiorcze kosztów jednostki TVP S.A.
        e22.pochodneOdWynagrodzenPoleTekstowe().should('have.attr', 'value', '47,50')
        e22.kosztyZewnetrznePoleTekstowe().should('have.attr', 'value', '4313,50')
        e22.kosztyBezposredniePoleTekstowe().should('have.attr', 'value', '9002,00')
        e22.kosztyPosredniePoleTekstowe().should('have.attr', 'value', '888,60')
        e22.kosztyRazemPoleTekstowe().should('have.attr', 'value', '10879,66')
        e22.kosztCalkNettoPoleTekstowe().should('have.attr', 'value', '11967,63')
        e22.vatPoleTekstowe().should('have.attr', 'value', '0,00')
        e22.vatOdPrawPoleTekstowe().should('have.attr', 'value', '16,04')
        e22.cenaSprzedazyPoleTekstowe().should('have.attr', 'value', '11867,63')
        // Wskaźniki
        e22.edytujWskaznikiPrzycisk().click()
        e224.jednostkaRozliczeniowaPoleTekstowe().siblings('input.form-control').should('have.attr', 'value', 'Jedn.Koszt.TVP')
        e224.narzutKosztowPosrPoleTekstowe().should('have.prop', 'value', '10,00 %')
        e224.vatPZPoleTekstowe().should('have.attr', 'value', '0,00')
        e224.vatWKosztachPoleTekstowe().should('have.prop', 'value', '69,74 %')
        e224.zusOdWynagrodzenPoleTekstowe().should('have.prop', 'value', '19,00 %')
        e224.sredniaOdWynagrodzenPoleTekstowe().should('have.attr', 'value', '0,00')
        e224.vatOdPrawPoleTekstowe().should('have.prop', 'value', '23,00 %')
        e224.powrotPrzycisk().click()

        cy.log('Krok 12 - Zmieniam wartość vat PZ we wskaźnikach i weryfikuję dane porozumienia')
        e22.edytujWskaznikiPrzycisk().click()
        e224.vatPZPoleTekstowe().clear().type('10')
        e224.zapiszPrzycisk().click()
        fWspolne.sprawdzProgressBar()
        e22.zapiszPrzycisk().click()
        fWspolne.sprawdzProgressBar()
        // Liczba odcinków 
        e22.liczbaOdcinkowPoleTekstowe().should('have.attr', 'value', 10)
        // Sprzedaż zewnętrzna
        e22.kozPoleTekstowe().should('have.prop', 'value', '10,00 %')
        e22.kosztyOgolnegoZarzadu1OdcPoleTekstowe().should('have.attr', 'value', '989,06')
        e22.kosztyOgolnegoZarzaduCalkPoleTekstowe().should('have.attr', 'value', '9890,60')
        e22.zyskPoleTekstowe().should('have.prop', 'value', '10,00 %')
        e22.zysk1OdcPoleTekstowe().should('have.attr', 'value', '1087,97')
        e22.zyskCalkowityPoleTekstowe().should('have.attr', 'value', '10879,66')
        // Kwoty cyklu
        e22.cenaSprzedazySumarycznaPoleTekstowe().should('have.attr', 'value', '130643,96')
        e22.wartoscPrawNabytychPoleTekstowe().should('have.attr', 'value', '1000,00')
        e22.przeniesieniePrawMajatkowychLista().find('option[selected]').contains('Wartość praw nie podlega amortyzacji')
        e22.wartoscMaterialowArchiwalnychPoleTekstowe().should('have.attr', 'value', '1000,00')
        e22.wynagrodzeniePracowniczePoleTekstowe().should('have.attr', 'value', '500,00')
        e22.wynagrodzenieWspolpracowniczePoleTekstowe().should('have.attr', 'value', '23000,00')
        e22.wartFinansZInJednPoleTekstowe().should('have.attr', 'value', '1000,00')
        // Zestawienie zbiorcze kosztów jednostki TVP S.A.
        e22.pochodneOdWynagrodzenPoleTekstowe().should('have.attr', 'value', '47,50')
        e22.kosztyZewnetrznePoleTekstowe().should('have.attr', 'value', '4313,50')
        e22.kosztyBezposredniePoleTekstowe().should('have.attr', 'value', '9002,00')
        e22.kosztyPosredniePoleTekstowe().should('have.attr', 'value', '888,60')
        e22.kosztyRazemPoleTekstowe().should('have.attr', 'value', '10879,66')
        e22.kosztCalkNettoPoleTekstowe().should('have.attr', 'value', '11967,63')
        e22.vatPoleTekstowe().should('have.attr', 'value', '1196,76')
        e22.vatOdPrawPoleTekstowe().should('have.attr', 'value', '16,04')
        e22.cenaSprzedazyPoleTekstowe().should('have.attr', 'value', '13064,39')
        // Wskaźniki
        e22.edytujWskaznikiPrzycisk().click()
        e224.jednostkaRozliczeniowaPoleTekstowe().siblings('input.form-control').should('have.attr', 'value', 'Jedn.Koszt.TVP')
        e224.narzutKosztowPosrPoleTekstowe().should('have.prop', 'value', '10,00 %')
        e224.vatPZPoleTekstowe().should('have.prop', 'value', '10,00 %')
        e224.vatWKosztachPoleTekstowe().should('have.prop', 'value', '69,74 %')
        e224.zusOdWynagrodzenPoleTekstowe().should('have.prop', 'value', '19,00 %')
        e224.sredniaOdWynagrodzenPoleTekstowe().should('have.attr', 'value', '0,00')
        e224.vatOdPrawPoleTekstowe().should('have.prop', 'value', '23,00 %')
        e224.powrotPrzycisk().click()

        cy.log('Krok 13 - Przywracam początkową liczbę odcinków i weryfikuję dane porozumienia')
        e22.liczbaOdcinkowPoleTekstowe().clear().type('1')
        e22.zapiszPrzycisk().click()
        e22.potwierdzLiczbeOdcinkowPopupPrzycisk().click()
        fWspolne.sprawdzProgressBar()
        // Liczba odcinków 
        e22.liczbaOdcinkowPoleTekstowe().should('have.attr', 'value', 1)
        // Sprzedaż zewnętrzna
        e22.kozPoleTekstowe().should('have.prop', 'value', '10,00 %')
        e22.kosztyOgolnegoZarzadu1OdcPoleTekstowe().should('have.attr', 'value', '3375,21')
        e22.kosztyOgolnegoZarzaduCalkPoleTekstowe().should('have.attr', 'value', '3375,21')
        e22.zyskPoleTekstowe().should('have.prop', 'value', '10,00 %')
        e22.zysk1OdcPoleTekstowe().should('have.attr', 'value', '3712,73')
        e22.zyskCalkowityPoleTekstowe().should('have.attr', 'value', '3712,73')
        // Kwoty cyklu
        e22.cenaSprzedazySumarycznaPoleTekstowe().should('have.attr', 'value', '43924,07')
        e22.wartoscPrawNabytychPoleTekstowe().should('have.attr', 'value', '1000,00')
        e22.przeniesieniePrawMajatkowychLista().find('option[selected]').contains('Wartość praw nie podlega amortyzacji')
        e22.wartoscMaterialowArchiwalnychPoleTekstowe().should('have.attr', 'value', '1000,00')
        e22.wynagrodzeniePracowniczePoleTekstowe().should('have.attr', 'value', '500,00')
        e22.wynagrodzenieWspolpracowniczePoleTekstowe().should('have.attr', 'value', '23000,00')
        e22.wartFinansZInJednPoleTekstowe().should('have.attr', 'value', '1000,00')
        // Zestawienie zbiorcze kosztów jednostki TVP S.A.
        e22.pochodneOdWynagrodzenPoleTekstowe().should('have.attr', 'value', '47,50')
        e22.kosztyZewnetrznePoleTekstowe().should('have.attr', 'value', '14757,12')
        e22.kosztyBezposredniePoleTekstowe().should('have.attr', 'value', '30789,24')
        e22.kosztyPosredniePoleTekstowe().should('have.attr', 'value', '2962,88')
        e22.kosztyRazemPoleTekstowe().should('have.attr', 'value', '37127,33')
        e22.kosztCalkNettoPoleTekstowe().should('have.attr', 'value', '40840,06')
        e22.vatPoleTekstowe().should('have.attr', 'value', '4084,01')
        e22.vatOdPrawPoleTekstowe().should('have.attr', 'value', '160,40')
        e22.cenaSprzedazyPoleTekstowe().should('have.attr', 'value', '43924,07')
        // Wskaźniki
        e22.edytujWskaznikiPrzycisk().click()
        e224.jednostkaRozliczeniowaPoleTekstowe().siblings('input.form-control').should('have.attr', 'value', 'Jedn.Koszt.TVP')
        e224.narzutKosztowPosrPoleTekstowe().should('have.prop', 'value', '10,00 %')
        e224.vatPZPoleTekstowe().should('have.prop', 'value', '10,00 %')
        e224.vatWKosztachPoleTekstowe().should('have.prop', 'value', '69,74 %')
        e224.zusOdWynagrodzenPoleTekstowe().should('have.prop', 'value', '19,00 %')
        e224.sredniaOdWynagrodzenPoleTekstowe().should('have.attr', 'value', '0,00')
        e224.vatOdPrawPoleTekstowe().should('have.prop', 'value', '23,00 %')
        e224.powrotPrzycisk().click()

        cy.log('Krok 14 - Przywracam początkową wartość vat PZ i weryfikuję dane porozumienia')
        e22.edytujWskaznikiPrzycisk().click()
        e224.vatPZPoleTekstowe().clear().type('0')
        e224.zapiszPrzycisk().click()
        fWspolne.sprawdzProgressBar()
        e22.zapiszPrzycisk().click()
        fWspolne.sprawdzProgressBar()
        // Liczba odcinków 
        e22.liczbaOdcinkowPoleTekstowe().should('have.attr', 'value', 1)
        // Sprzedaż zewnętrzna
        e22.kozPoleTekstowe().should('have.prop', 'value', '10,00 %')
        e22.kosztyOgolnegoZarzadu1OdcPoleTekstowe().should('have.attr', 'value', '3375,21')
        e22.kosztyOgolnegoZarzaduCalkPoleTekstowe().should('have.attr', 'value', '3375,21')
        e22.zyskPoleTekstowe().should('have.prop', 'value', '10,00 %')
        e22.zysk1OdcPoleTekstowe().should('have.attr', 'value', '3712,73')
        e22.zyskCalkowityPoleTekstowe().should('have.attr', 'value', '3712,73')
        // Kwoty cyklu
        e22.cenaSprzedazySumarycznaPoleTekstowe().should('have.attr', 'value', '39840,06')
        e22.wartoscPrawNabytychPoleTekstowe().should('have.attr', 'value', '1000,00')
        e22.przeniesieniePrawMajatkowychLista().find('option[selected]').contains('Wartość praw nie podlega amortyzacji')
        e22.wartoscMaterialowArchiwalnychPoleTekstowe().should('have.attr', 'value', '1000,00')
        e22.wynagrodzeniePracowniczePoleTekstowe().should('have.attr', 'value', '500,00')
        e22.wynagrodzenieWspolpracowniczePoleTekstowe().should('have.attr', 'value', '23000,00')
        e22.wartFinansZInJednPoleTekstowe().should('have.attr', 'value', '1000,00')
        // Zestawienie zbiorcze kosztów jednostki TVP S.A.
        e22.pochodneOdWynagrodzenPoleTekstowe().should('have.attr', 'value', '47,50')
        e22.kosztyZewnetrznePoleTekstowe().should('have.attr', 'value', '14757,12')
        e22.kosztyBezposredniePoleTekstowe().should('have.attr', 'value', '30789,24')
        e22.kosztyPosredniePoleTekstowe().should('have.attr', 'value', '2962,88')
        e22.kosztyRazemPoleTekstowe().should('have.attr', 'value', '37127,33')
        e22.kosztCalkNettoPoleTekstowe().should('have.attr', 'value', '40840,06')
        e22.vatPoleTekstowe().should('have.attr', 'value', '0,00')
        e22.vatOdPrawPoleTekstowe().should('have.attr', 'value', '160,40')
        e22.cenaSprzedazyPoleTekstowe().should('have.attr', 'value', '39840,06')
        // Wskaźniki
        e22.edytujWskaznikiPrzycisk().click()
        e224.jednostkaRozliczeniowaPoleTekstowe().siblings('input.form-control').should('have.attr', 'value', 'Jedn.Koszt.TVP')
        e224.narzutKosztowPosrPoleTekstowe().should('have.prop', 'value', '10,00 %')
        e224.vatPZPoleTekstowe().should('have.attr', 'value', '0,00')
        e224.vatWKosztachPoleTekstowe().should('have.prop', 'value', '69,74 %')
        e224.zusOdWynagrodzenPoleTekstowe().should('have.prop', 'value', '19,00 %')
        e224.sredniaOdWynagrodzenPoleTekstowe().should('have.attr', 'value', '0,00')
        e224.vatOdPrawPoleTekstowe().should('have.prop', 'value', '23,00 %')
        e224.powrotPrzycisk().click()

        cy.log('Krok 15 - Przywracam początkową wartość narzutu kosztów pośrednich i weryfikuję dane porozumienia')
        e22.edytujWskaznikiPrzycisk().click()
        e224.narzutKosztowPosrPoleTekstowe().clear().type('0')
        e224.zapiszPrzycisk().click()
        fWspolne.sprawdzProgressBar()
        e22.zapiszPrzycisk().click()
        fWspolne.sprawdzProgressBar()
        // Liczba odcinków 
        e22.liczbaOdcinkowPoleTekstowe().should('have.attr', 'value', 1)
        // Sprzedaż zewnętrzna
        e22.kozPoleTekstowe().should('have.prop', 'value', '10,00 %')
        e22.kosztyOgolnegoZarzadu1OdcPoleTekstowe().should('have.attr', 'value', '2951,42')
        e22.kosztyOgolnegoZarzaduCalkPoleTekstowe().should('have.attr', 'value', '2951,42')
        e22.zyskPoleTekstowe().should('have.prop', 'value', '10,00 %')
        e22.zysk1OdcPoleTekstowe().should('have.attr', 'value', '3246,57')
        e22.zyskCalkowityPoleTekstowe().should('have.attr', 'value', '3246,57')
        // Kwoty cyklu
        e22.cenaSprzedazySumarycznaPoleTekstowe().should('have.attr', 'value', '34712,23')
        e22.wartoscPrawNabytychPoleTekstowe().should('have.attr', 'value', '1000,00')
        e22.przeniesieniePrawMajatkowychLista().find('option[selected]').contains('Wartość praw nie podlega amortyzacji')
        e22.wartoscMaterialowArchiwalnychPoleTekstowe().should('have.attr', 'value', '1000,00')
        e22.wynagrodzeniePracowniczePoleTekstowe().should('have.attr', 'value', '500,00')
        e22.wynagrodzenieWspolpracowniczePoleTekstowe().should('have.attr', 'value', '23000,00')
        e22.wartFinansZInJednPoleTekstowe().should('have.attr', 'value', '1000,00')
        // Zestawienie zbiorcze kosztów jednostki TVP S.A.
        e22.pochodneOdWynagrodzenPoleTekstowe().should('have.attr', 'value', '47,50')
        e22.kosztyZewnetrznePoleTekstowe().should('have.attr', 'value', '14757,12')
        e22.kosztyBezposredniePoleTekstowe().should('have.attr', 'value', '29514,24')
        e22.kosztyPosredniePoleTekstowe().should('have.attr', 'value', '0,00')
        e22.kosztyRazemPoleTekstowe().should('have.attr', 'value', '32465,66')
        e22.kosztCalkNettoPoleTekstowe().should('have.attr', 'value', '35712,23')
        e22.vatPoleTekstowe().should('have.attr', 'value', '0,00')
        e22.vatOdPrawPoleTekstowe().should('have.attr', 'value', '160,40')
        e22.cenaSprzedazyPoleTekstowe().should('have.attr', 'value', '34712,23')
        // Wskaźniki
        e22.edytujWskaznikiPrzycisk().click()
        e224.jednostkaRozliczeniowaPoleTekstowe().siblings('input.form-control').should('have.attr', 'value', 'Jedn.Koszt.TVP')
        e224.narzutKosztowPosrPoleTekstowe().should('have.attr', 'value', '0,00')
        e224.vatPZPoleTekstowe().should('have.attr', 'value', '0,00')
        e224.vatWKosztachPoleTekstowe().should('have.prop', 'value', '69,74 %')
        e224.zusOdWynagrodzenPoleTekstowe().should('have.prop', 'value', '19,00 %')
        e224.sredniaOdWynagrodzenPoleTekstowe().should('have.attr', 'value', '0,00')
        e224.vatOdPrawPoleTekstowe().should('have.prop', 'value', '23,00 %')
        e224.powrotPrzycisk().click()

        cy.log('Krok 16 - Przywracam domyślną wartość w polu Przeniesienie praw majątkowych i weryfikuję dane porozumienia')
        e22.przeniesieniePrawMajatkowychLista().select('Wartość praw podlega amortyzacji', {force: true})
        e22.zapiszPrzycisk().click()
        fWspolne.sprawdzProgressBar() 
        // Liczba odcinków 
        e22.liczbaOdcinkowPoleTekstowe().should('have.attr', 'value', 1)
        // Sprzedaż zewnętrzna
        e22.kozPoleTekstowe().should('have.prop', 'value', '10,00 %')
        e22.kosztyOgolnegoZarzadu1OdcPoleTekstowe().should('have.attr', 'value', '2951,42')
        e22.kosztyOgolnegoZarzaduCalkPoleTekstowe().should('have.attr', 'value', '2951,42')
        e22.zyskPoleTekstowe().should('have.prop', 'value', '10,00 %')
        e22.zysk1OdcPoleTekstowe().should('have.attr', 'value', '3246,57')
        e22.zyskCalkowityPoleTekstowe().should('have.attr', 'value', '3246,57')
        // Kwoty cyklu
        e22.cenaSprzedazySumarycznaPoleTekstowe().should('have.attr', 'value', '34712,23')
        e22.wartoscPrawNabytychPoleTekstowe().should('have.attr', 'value', '1000,00')
        e22.przeniesieniePrawMajatkowychLista().find('option[selected]').contains('Wartość praw podlega amortyzacji')
        e22.wartoscMaterialowArchiwalnychPoleTekstowe().should('have.attr', 'value', '1000,00')
        e22.wynagrodzeniePracowniczePoleTekstowe().should('have.attr', 'value', '500,00')
        e22.wynagrodzenieWspolpracowniczePoleTekstowe().should('have.attr', 'value', '23000,00')
        e22.wartFinansZInJednPoleTekstowe().should('have.attr', 'value', '1000,00')
        // Zestawienie zbiorcze kosztów jednostki TVP S.A.
        e22.pochodneOdWynagrodzenPoleTekstowe().should('have.attr', 'value', '47,50')
        e22.kosztyZewnetrznePoleTekstowe().should('have.attr', 'value', '14757,12')
        e22.kosztyBezposredniePoleTekstowe().should('have.attr', 'value', '29514,24')
        e22.kosztyPosredniePoleTekstowe().should('have.attr', 'value', '0,00')
        e22.kosztyRazemPoleTekstowe().should('have.attr', 'value', '32465,66')
        e22.kosztCalkNettoPoleTekstowe().should('have.attr', 'value', '35712,23')
        e22.vatPoleTekstowe().should('have.attr', 'value', '0,00')
        e22.vatOdPrawPoleTekstowe().should('have.attr', 'value', '160,40')
        e22.cenaSprzedazyPoleTekstowe().should('have.attr', 'value', '34712,23')
        // Wskaźniki
        e22.edytujWskaznikiPrzycisk().click()
        e224.jednostkaRozliczeniowaPoleTekstowe().siblings('input.form-control').should('have.attr', 'value', 'Jedn.Koszt.TVP')
        e224.narzutKosztowPosrPoleTekstowe().should('have.attr', 'value', '0,00')
        e224.vatPZPoleTekstowe().should('have.attr', 'value', '0,00')
        e224.vatWKosztachPoleTekstowe().should('have.prop', 'value', '69,74 %')
        e224.zusOdWynagrodzenPoleTekstowe().should('have.prop', 'value', '19,00 %')
        e224.sredniaOdWynagrodzenPoleTekstowe().should('have.attr', 'value', '0,00')
        e224.vatOdPrawPoleTekstowe().should('have.prop', 'value', '23,00 %')
        e224.powrotPrzycisk().click()

        cy.log('Krok 17 - Przywracam domyślną wartość finansowania z innych jednostek i weryfikuję dane porozumienia')
        e22.wartFinansZInJednPoleTekstowe().clear().type('0')
        e22.zapiszPrzycisk().click()
        fWspolne.sprawdzProgressBar()
        // Liczba odcinków 
        e22.liczbaOdcinkowPoleTekstowe().should('have.attr', 'value', 1)
        // Sprzedaż zewnętrzna
        e22.kozPoleTekstowe().should('have.prop', 'value', '10,00 %')
        e22.kosztyOgolnegoZarzadu1OdcPoleTekstowe().should('have.attr', 'value', '2951,42')
        e22.kosztyOgolnegoZarzaduCalkPoleTekstowe().should('have.attr', 'value', '2951,42')
        e22.zyskPoleTekstowe().should('have.prop', 'value', '10,00 %')
        e22.zysk1OdcPoleTekstowe().should('have.attr', 'value', '3246,57')
        e22.zyskCalkowityPoleTekstowe().should('have.attr', 'value', '3246,57')
        // Kwoty cyklu
        e22.cenaSprzedazySumarycznaPoleTekstowe().should('have.attr', 'value', '35712,23')
        e22.wartoscPrawNabytychPoleTekstowe().should('have.attr', 'value', '1000,00')
        e22.przeniesieniePrawMajatkowychLista().find('option[selected]').contains('Wartość praw podlega amortyzacji')
        e22.wartoscMaterialowArchiwalnychPoleTekstowe().should('have.attr', 'value', '1000,00')
        e22.wynagrodzeniePracowniczePoleTekstowe().should('have.attr', 'value', '500,00')
        e22.wynagrodzenieWspolpracowniczePoleTekstowe().should('have.attr', 'value', '23000,00')
        e22.wartFinansZInJednPoleTekstowe().should('have.attr', 'value', '0,00')
        // Zestawienie zbiorcze kosztów jednostki TVP S.A.
        e22.pochodneOdWynagrodzenPoleTekstowe().should('have.attr', 'value', '47,50')
        e22.kosztyZewnetrznePoleTekstowe().should('have.attr', 'value', '14757,12')
        e22.kosztyBezposredniePoleTekstowe().should('have.attr', 'value', '29514,24')
        e22.kosztyPosredniePoleTekstowe().should('have.attr', 'value', '0,00')
        e22.kosztyRazemPoleTekstowe().should('have.attr', 'value', '32465,66')
        e22.kosztCalkNettoPoleTekstowe().should('have.attr', 'value', '35712,23')
        e22.vatPoleTekstowe().should('have.attr', 'value', '0,00')
        e22.vatOdPrawPoleTekstowe().should('have.attr', 'value', '160,40')
        e22.cenaSprzedazyPoleTekstowe().should('have.attr', 'value', '35712,23')
        // Wskaźniki
        e22.edytujWskaznikiPrzycisk().click()
        e224.jednostkaRozliczeniowaPoleTekstowe().siblings('input.form-control').should('have.attr', 'value', 'Jedn.Koszt.TVP')
        e224.narzutKosztowPosrPoleTekstowe().should('have.attr', 'value', '0,00')
        e224.vatPZPoleTekstowe().should('have.attr', 'value', '0,00')
        e224.vatWKosztachPoleTekstowe().should('have.prop', 'value', '69,74 %')
        e224.zusOdWynagrodzenPoleTekstowe().should('have.prop', 'value', '19,00 %')
        e224.sredniaOdWynagrodzenPoleTekstowe().should('have.attr', 'value', '0,00')
        e224.vatOdPrawPoleTekstowe().should('have.prop', 'value', '23,00 %')
        e224.powrotPrzycisk().click()

        cy.log('Krok 18 - Przywracam domyślną wartość praw mat. arch. i weryfikuję dane porozumienia')
        e22.wartoscMaterialowArchiwalnychPoleTekstowe().clear().type('0')
        e22.zapiszPrzycisk().click()
        fWspolne.sprawdzProgressBar()
        // Liczba odcinków
        e22.liczbaOdcinkowPoleTekstowe().should('have.attr', 'value', 1)
        // Sprzedaż zewnętrzna
        e22.kozPoleTekstowe().should('have.prop', 'value', '10,00 %')
        e22.kosztyOgolnegoZarzadu1OdcPoleTekstowe().should('have.attr', 'value', '2951,42')
        e22.kosztyOgolnegoZarzaduCalkPoleTekstowe().should('have.attr', 'value', '2951,42')
        e22.zyskPoleTekstowe().should('have.prop', 'value', '10,00 %')
        e22.zysk1OdcPoleTekstowe().should('have.attr', 'value', '3246,57')
        e22.zyskCalkowityPoleTekstowe().should('have.attr', 'value', '3246,57')
        // Kwoty cyklu
        e22.cenaSprzedazySumarycznaPoleTekstowe().should('have.attr', 'value', '35712,23')
        e22.wartoscPrawNabytychPoleTekstowe().should('have.attr', 'value', '1000,00')
        e22.przeniesieniePrawMajatkowychLista().find('option[selected]').contains('Wartość praw podlega amortyzacji')
        e22.wartoscMaterialowArchiwalnychPoleTekstowe().should('have.attr', 'value', '0,00')
        e22.wynagrodzeniePracowniczePoleTekstowe().should('have.attr', 'value', '500,00')
        e22.wynagrodzenieWspolpracowniczePoleTekstowe().should('have.attr', 'value', '23000,00')
        e22.wartFinansZInJednPoleTekstowe().should('have.attr', 'value', '0,00')
        // Zestawienie zbiorcze kosztów jednostki TVP S.A.
        e22.pochodneOdWynagrodzenPoleTekstowe().should('have.attr', 'value', '47,50')
        e22.kosztyZewnetrznePoleTekstowe().should('have.attr', 'value', '14757,12')
        e22.kosztyBezposredniePoleTekstowe().should('have.attr', 'value', '29514,24')
        e22.kosztyPosredniePoleTekstowe().should('have.attr', 'value', '0,00')
        e22.kosztyRazemPoleTekstowe().should('have.attr', 'value', '32465,66')
        e22.kosztCalkNettoPoleTekstowe().should('have.attr', 'value', '35712,23')
        e22.vatPoleTekstowe().should('have.attr', 'value', '0,00')
        e22.vatOdPrawPoleTekstowe().should('have.attr', 'value', '160,40')
        e22.cenaSprzedazyPoleTekstowe().should('have.attr', 'value', '35712,23')
        // Wskaźniki
        e22.edytujWskaznikiPrzycisk().click()
        e224.jednostkaRozliczeniowaPoleTekstowe().siblings('input.form-control').should('have.attr', 'value', 'Jedn.Koszt.TVP')
        e224.narzutKosztowPosrPoleTekstowe().should('have.attr', 'value', '0,00')
        e224.vatPZPoleTekstowe().should('have.attr', 'value', '0,00')
        e224.vatWKosztachPoleTekstowe().should('have.prop', 'value', '69,74 %')
        e224.zusOdWynagrodzenPoleTekstowe().should('have.prop', 'value', '19,00 %')
        e224.sredniaOdWynagrodzenPoleTekstowe().should('have.attr', 'value', '0,00')
        e224.vatOdPrawPoleTekstowe().should('have.prop', 'value', '23,00 %')
        e224.powrotPrzycisk().click()

        cy.log('Krok 19 - Przywracam domyślną wartość praw nabytych i weryfikuję dane porozumienia')
        e22.wartoscPrawNabytychPoleTekstowe().clear().type('0')
        e22.zapiszPrzycisk().click()
        fWspolne.sprawdzProgressBar()
        // Liczba odcinków
        e22.liczbaOdcinkowPoleTekstowe().should('have.attr', 'value', 1)
        // Sprzedaż zewnętrzna
        e22.kozPoleTekstowe().should('have.prop', 'value', '10,00 %')
        e22.kosztyOgolnegoZarzadu1OdcPoleTekstowe().should('have.attr', 'value', '2951,42')
        e22.kosztyOgolnegoZarzaduCalkPoleTekstowe().should('have.attr', 'value', '2951,42')
        e22.zyskPoleTekstowe().should('have.prop', 'value', '10,00 %')
        e22.zysk1OdcPoleTekstowe().should('have.attr', 'value', '3246,57')
        e22.zyskCalkowityPoleTekstowe().should('have.attr', 'value', '3246,57')
        // Kwoty cyklu
        e22.cenaSprzedazySumarycznaPoleTekstowe().should('have.attr', 'value', '35712,23')
        e22.wartoscPrawNabytychPoleTekstowe().should('have.attr', 'value', '0,00')
        e22.przeniesieniePrawMajatkowychLista().find('option[selected]').contains('Wartość praw podlega amortyzacji')
        e22.wartoscMaterialowArchiwalnychPoleTekstowe().should('have.attr', 'value', '0,00')
        e22.wynagrodzeniePracowniczePoleTekstowe().should('have.attr', 'value', '500,00')
        e22.wynagrodzenieWspolpracowniczePoleTekstowe().should('have.attr', 'value', '23000,00')
        e22.wartFinansZInJednPoleTekstowe().should('have.attr', 'value', '0,00')
        // Zestawienie zbiorcze kosztów jednostki TVP S.A.
        e22.pochodneOdWynagrodzenPoleTekstowe().should('have.attr', 'value', '47,50')
        e22.kosztyZewnetrznePoleTekstowe().should('have.attr', 'value', '14757,12')
        e22.kosztyBezposredniePoleTekstowe().should('have.attr', 'value', '29514,24')
        e22.kosztyPosredniePoleTekstowe().should('have.attr', 'value', '0,00')
        e22.kosztyRazemPoleTekstowe().should('have.attr', 'value', '32465,66')
        e22.kosztCalkNettoPoleTekstowe().should('have.attr', 'value', '35712,23')
        e22.vatPoleTekstowe().should('have.attr', 'value', '0,00')
        e22.vatOdPrawPoleTekstowe().should('have.attr', 'value', '0,00')
        e22.cenaSprzedazyPoleTekstowe().should('have.attr', 'value', '35712,23')
        // Wskaźniki
        e22.edytujWskaznikiPrzycisk().click()
        e224.jednostkaRozliczeniowaPoleTekstowe().siblings('input.form-control').should('have.attr', 'value', 'Jedn.Koszt.TVP')
        e224.narzutKosztowPosrPoleTekstowe().should('have.attr', 'value', '0,00')
        e224.vatPZPoleTekstowe().should('have.attr', 'value', '0,00')
        e224.vatWKosztachPoleTekstowe().should('have.prop', 'value', '69,74 %')
        e224.zusOdWynagrodzenPoleTekstowe().should('have.prop', 'value', '19,00 %')
        e224.sredniaOdWynagrodzenPoleTekstowe().should('have.attr', 'value', '0,00')
        e224.vatOdPrawPoleTekstowe().should('have.prop', 'value', '23,00 %')
        e224.powrotPrzycisk().click()

        cy.log('Krok 20 - Przywracam domyślną wartość w polu Zysk i weryfikuję dane porozumienia')
        e22.zyskPoleTekstowe().clear().type('0')
        e22.zapiszPrzycisk().click()
        fWspolne.sprawdzProgressBar()
        // Liczba odcinków 
        e22.liczbaOdcinkowPoleTekstowe().should('have.attr', 'value', 1)
        // Sprzedaż zewnętrzna
        e22.kozPoleTekstowe().should('have.prop', 'value', '10,00 %')
        e22.kosztyOgolnegoZarzadu1OdcPoleTekstowe().should('have.attr', 'value', '2951,42')
        e22.kosztyOgolnegoZarzaduCalkPoleTekstowe().should('have.attr', 'value', '2951,42')
        e22.zyskPoleTekstowe().should('have.attr', 'value', '0,00')
        e22.zysk1OdcPoleTekstowe().should('have.attr', 'value', '0,00')
        e22.zyskCalkowityPoleTekstowe().should('have.attr', 'value', '0,00')
        // Kwoty cyklu
        e22.cenaSprzedazySumarycznaPoleTekstowe().should('have.attr', 'value', '32465,66')
        e22.wartoscPrawNabytychPoleTekstowe().should('have.attr', 'value', '0,00')
        e22.przeniesieniePrawMajatkowychLista().find('option[selected]').contains('Wartość praw podlega amortyzacji')
        e22.wartoscMaterialowArchiwalnychPoleTekstowe().should('have.attr', 'value', '0,00')
        e22.wynagrodzeniePracowniczePoleTekstowe().should('have.attr', 'value', '500,00')
        e22.wynagrodzenieWspolpracowniczePoleTekstowe().should('have.attr', 'value', '23000,00')
        e22.wartFinansZInJednPoleTekstowe().should('have.attr', 'value', '0,00')
        // Zestawienie zbiorcze kosztów jednostki TVP S.A.
        e22.pochodneOdWynagrodzenPoleTekstowe().should('have.attr', 'value', '47,50')
        e22.kosztyZewnetrznePoleTekstowe().should('have.attr', 'value', '14757,12')
        e22.kosztyBezposredniePoleTekstowe().should('have.attr', 'value', '29514,24')
        e22.kosztyPosredniePoleTekstowe().should('have.attr', 'value', '0,00')
        e22.kosztyRazemPoleTekstowe().should('have.attr', 'value', '32465,66')
        e22.kosztCalkNettoPoleTekstowe().should('have.attr', 'value', '32465,66')
        e22.vatPoleTekstowe().should('have.attr', 'value', '0,00')
        e22.vatOdPrawPoleTekstowe().should('have.attr', 'value', '0,00')
        e22.cenaSprzedazyPoleTekstowe().should('have.attr', 'value', '32465,66')
        // Wskaźniki
        e22.edytujWskaznikiPrzycisk().click()
        e224.jednostkaRozliczeniowaPoleTekstowe().siblings('input.form-control').should('have.attr', 'value', 'Jedn.Koszt.TVP')
        e224.narzutKosztowPosrPoleTekstowe().should('have.attr', 'value', '0,00')
        e224.vatPZPoleTekstowe().should('have.attr', 'value', '0,00')
        e224.vatWKosztachPoleTekstowe().should('have.prop', 'value', '69,74 %')
        e224.zusOdWynagrodzenPoleTekstowe().should('have.prop', 'value', '19,00 %')
        e224.sredniaOdWynagrodzenPoleTekstowe().should('have.attr', 'value', '0,00')
        e224.vatOdPrawPoleTekstowe().should('have.prop', 'value', '23,00 %')
        e224.powrotPrzycisk().click()

        cy.log('Krok 21 - Przywracam domyślną wartość w polu KOZ i weryfikuję dane porozumienia')
        e22.kozPoleTekstowe().clear().type('0')
        e22.zapiszPrzycisk().click()
        fWspolne.sprawdzProgressBar()
        // Liczba odcinków 
        e22.liczbaOdcinkowPoleTekstowe().should('have.attr', 'value', 1)
        // Sprzedaż zewnętrzna
        e22.kozPoleTekstowe().should('have.attr', 'value', '0,00')
        e22.kosztyOgolnegoZarzadu1OdcPoleTekstowe().should('have.attr', 'value', '0,00')
        e22.kosztyOgolnegoZarzaduCalkPoleTekstowe().should('have.attr', 'value', '0,00')
        e22.zyskPoleTekstowe().should('have.attr', 'value', '0,00')
        e22.zysk1OdcPoleTekstowe().should('have.attr', 'value', '0,00')
        e22.zyskCalkowityPoleTekstowe().should('have.attr', 'value', '0,00')
        // Kwoty cyklu
        e22.cenaSprzedazySumarycznaPoleTekstowe().should('have.attr', 'value', '29514,24')
        e22.wartoscPrawNabytychPoleTekstowe().should('have.attr', 'value', '0,00')
        e22.przeniesieniePrawMajatkowychLista().find('option[selected]').contains('Wartość praw podlega amortyzacji')
        e22.wartoscMaterialowArchiwalnychPoleTekstowe().should('have.attr', 'value', '0,00')
        e22.wynagrodzeniePracowniczePoleTekstowe().should('have.attr', 'value', '500,00')
        e22.wynagrodzenieWspolpracowniczePoleTekstowe().should('have.attr', 'value', '23000,00')
        e22.wartFinansZInJednPoleTekstowe().should('have.attr', 'value', '0,00')
        // Zestawienie zbiorcze kosztów jednostki TVP S.A.
        e22.pochodneOdWynagrodzenPoleTekstowe().should('have.attr', 'value', '47,50')
        e22.kosztyZewnetrznePoleTekstowe().should('have.attr', 'value', '14757,12')
        e22.kosztyBezposredniePoleTekstowe().should('have.attr', 'value', '29514,24')
        e22.kosztyPosredniePoleTekstowe().should('have.attr', 'value', '0,00')
        e22.kosztyRazemPoleTekstowe().should('have.attr', 'value', '29514,24')
        e22.kosztCalkNettoPoleTekstowe().should('have.attr', 'value', '29514,24')
        e22.vatPoleTekstowe().should('have.attr', 'value', '0,00')
        e22.vatOdPrawPoleTekstowe().should('have.attr', 'value', '0,00')
        e22.cenaSprzedazyPoleTekstowe().should('have.attr', 'value', '29514,24')
        // Wskaźniki
        e22.edytujWskaznikiPrzycisk().click()
        e224.jednostkaRozliczeniowaPoleTekstowe().siblings('input.form-control').should('have.attr', 'value', 'Jedn.Koszt.TVP')
        e224.narzutKosztowPosrPoleTekstowe().should('have.attr', 'value', '0,00')
        e224.vatPZPoleTekstowe().should('have.attr', 'value', '0,00')
        e224.vatWKosztachPoleTekstowe().should('have.prop', 'value', '69,74 %')
        e224.zusOdWynagrodzenPoleTekstowe().should('have.prop', 'value', '19,00 %')
        e224.sredniaOdWynagrodzenPoleTekstowe().should('have.attr', 'value', '0,00')
        e224.vatOdPrawPoleTekstowe().should('have.prop', 'value', '23,00 %')
        e224.powrotPrzycisk().click()

        // Wylogowanie
        cy.logoutUser()
    })
})