import { fWspolne } from '../../../../POM/Funkcje wspolne/Funkcje wspolne'
import { e20 } from '../../../../POM/Planowanie/E20 Porozumienia'
import { e22 } from '../../../../POM/Planowanie/E22 Porozumienia - szczegoly'
import { e501 } from '../../../../POM/Produkcja/Wnioski o przydzielenie zasobow/E501 Wniosek o przydzielenie zasobów - wyszukiwarka'
import { e502 } from '../../../../POM/Produkcja/Wnioski o przydzielenie zasobow/E502 Wniosek o przydzielenie zasobów - szczegoly'
import { e50200 } from '../../../../POM/Produkcja/Wnioski o przydzielenie zasobow/E502.00 Wniosek o przydzielenie zasobow - wykorzystanie zasobow'
import { e50201 } from '../../../../POM/Produkcja/Wnioski o przydzielenie zasobow/E502.01 Wniosek o przydzielenie zasobow - szczegoly rezerwacji'

describe('SEPP-18072 Walidacja SAP w zależności od rodzaju porozumienia', () => {
    it('Walidacja SAP dla rodzaju: produkcyjne', () => {
        cy.log('Krok 1 - Loguję się jako Producent') 
        cy.visit('/')
            .loginProducent()

        cy.log('Krok 2 - Jestem na ekranie listy porozumień i przechodzę na ekran edycji wybranego porozumienia')
        cy.goToMenu('Porozumienia')
        e20.nazwaAudycjiTVPoleTekstowe().type('SEPP-18072')
        e20.wyszukajPrzycisk().click()
        fWspolne.sprawdzProgressBar()
        e20.edycjaPierwszyPrzycisk().click()
        fWspolne.sprawdzProgressBar()
        
        cy.log('Krok 3 - Weryfikuję rodzaj porozumienia')
        e22.rodzajPorozumieniaLista().find('option[selected]').contains('produkcyjne')

        cy.log('Krok 4 - Jestem na ekranie listy wniosków o zasoby i przechodzę na ekran edycji wybranego wniosku')
        cy.goToMenu('Wnioski o przydzielenie zasobów')
        e501.nazwaAudycjiTVPoleTekstowe().type('SEPP-18072')
        e501.wyszukajPrzycisk().click()
        fWspolne.sprawdzProgressBar()
        e501.edytujWniosekPierwszyPrzycisk().click()

        cy.log('Krok 5 - Wyszukuję wybraną rezerwację')
        e502.rezerwacjaPrzyciskWyboru(0).check()
        e502.zlozZamowieniePrzycisk().should('be.visible')

        cy.log('Krok 6 - Przechodzę do edycji wybranej rezerwacji i sprawdzam czy przypisano odcinek nr 2')
        e502.edycjaRezerwacjiPierwszyPrzycisk().click()
        cy.get('#daysTable > tbody > tr > td:nth-child(6)').should('have.prop', 'outerText', '2')

        cy.log('Krok 7 - Składam zamówienie i sprawdzam czy wystąpi walidacja numerów kontrolingowych')
        e50201.zlozZamowieniePrzycisk().click()
        e50201.takZlozPopupPrzycisk().click()
        cy.get('div#sendToRealizationErrorContainer').contains('W sekcji Technika studyjna, w dniu 26.09.2024 wskazano audycję, która nie ma uzupełnionych identyfikatorów obiektów kontrolingowych SAP. Proszę uzupełnić dane i spróbować ponownie przekazać wniosek do dyspozytury.')
        cy.get('button#sendToRealizationError-noBtn').click().should('not.exist')

        cy.log('Krok 8 - Ponawiam krok 7 po przypisaniu kolejno odcinka 3 i 4')
        e50201.audycjePierwszyPrzycisk().click()
        e50201.audycjaPopupPrzyciskWyboru(1).uncheck()
        e50201.audycjaPopupPrzyciskWyboru(2).check()
        e50201.potwierdzAudycjePopupPrzycisk().click()
        e50201.zlozZamowieniePrzycisk().click()
        e50201.takZlozPopupPrzycisk().click()
        cy.get('div#sendToRealizationErrorContainer').contains('W sekcji Technika studyjna, w dniu 26.09.2024 wskazano audycję, która nie ma uzupełnionych identyfikatorów obiektów kontrolingowych SAP. Proszę uzupełnić dane i spróbować ponownie przekazać wniosek do dyspozytury.')
        cy.get('button#sendToRealizationError-noBtn').click().should('not.exist')
        e50201.audycjePierwszyPrzycisk().click()
        e50201.audycjaPopupPrzyciskWyboru(2).uncheck()
        e50201.audycjaPopupPrzyciskWyboru(3).check()
        e50201.potwierdzAudycjePopupPrzycisk().click()
        e50201.zlozZamowieniePrzycisk().click()
        e50201.takZlozPopupPrzycisk().click()
        cy.get('div#sendToRealizationErrorContainer').contains('W sekcji Technika studyjna, w dniu 26.09.2024 wskazano audycję, która nie ma uzupełnionych identyfikatorów obiektów kontrolingowych SAP. Proszę uzupełnić dane i spróbować ponownie przekazać wniosek do dyspozytury.')
        cy.get('button#sendToRealizationError-noBtn').click().should('not.exist')

        cy.log('Krok 9 - Przypisuję odcinek 1 i składam zamówienie')
        e50201.audycjePierwszyPrzycisk().click()
        e50201.audycjaPopupPrzyciskWyboru(3).uncheck()
        e50201.audycjaPopupPrzyciskWyboru(0).check()
        e50201.potwierdzAudycjePopupPrzycisk().click()
        e50201.zlozZamowieniePrzycisk().click()
        e50201.takZlozPopupPrzycisk().click()
        fWspolne.sprawdzProgressBar()
        e50201.statusRezerwacjiEtykieta().should('have.value', 'Przekazano do dyspozytury (zamówienie)')

        cy.log('Krok 10 - Przelogowuję się na dyspozytora i odrzucam rezerwację')
        cy.logoutUser()
        cy.loginPracownikDyspozytury()
        cy.goToMenu('Wnioski o przydzielenie zasobów')
        e501.nazwaAudycjiTVPoleTekstowe().type('SEPP-18072')
        e501.wyszukajPrzycisk().click()
        fWspolne.sprawdzProgressBar()
        e501.edytujSekcjeWnioskuPierwszyPrzycisk().click()
        e50200.odrzucPrzycisk().click()
        e50200.takOdrzucPopupPrzycisk().click()
        e50200.powodOdrzuceniaPopupPoleTekstowe().type('odrzucam')
        e50200.potwierdzPopupPrzycisk().click()
        fWspolne.sprawdzProgressBar()
        cy.logoutUser()
    })

    it('Walidacja SAP dla rodzaju: prace przygotowawcze', () => {
        cy.log('Krok 11 - Przelogowuję się ponownie na producenta i przechodzę do wybranego porozumienia')
        cy.loginProducent()
        cy.goToMenu('Porozumienia')
        e20.nazwaAudycjiTVPoleTekstowe().type('SEPP-18072')
        e20.wyszukajPrzycisk().click()
        fWspolne.sprawdzProgressBar()
        e20.edycjaPierwszyPrzycisk().click()
        fWspolne.sprawdzProgressBar()

        cy.log('Krok 12 - Zmieniam rodzaj porozumienia na: prace przygotowawcze')
        e22.rodzajPorozumieniaLista().select('prace przygotowawcze', {force: true})
        e22.agencjaLista().find('option[selected]').should('contain.text', 'AKFiS')
        e22.zapiszPrzycisk().click()
        fWspolne.sprawdzProgressBar()

        cy.log('Krok 13 - Jestem na ekranie listy wniosków o zasoby i przechodzę na ekran edycji wybranego wniosku')
        cy.goToMenu('Wnioski o przydzielenie zasobów')
        e501.nazwaAudycjiTVPoleTekstowe().type('SEPP-18072')
        e501.wyszukajPrzycisk().click()
        fWspolne.sprawdzProgressBar()
        e501.edytujWniosekPierwszyPrzycisk().click()

        cy.log('Krok 14 - Wyszukuję wybraną rezerwację i przechodzę do jej edycji')
        e502.edycjaRezerwacjiPierwszyPrzycisk().click()

        cy.log('Krok 15 - Sprawdzam czy przypisano odcinek nr 1, a następnie składam zamówienie i sprawdzam czy wystąpi walidacja numerów kontrolingowych')
        cy.get('#daysTable > tbody > tr > td:nth-child(6)').should('have.prop', 'outerText', '1')
        e50201.zlozZamowieniePrzycisk().click()
        e50201.takZlozPopupPrzycisk().click()
        cy.get('div#sendToRealizationErrorContainer').contains('W sekcji Technika studyjna, w dniu 26.09.2024 wskazano audycję, która nie ma uzupełnionych identyfikatorów obiektów kontrolingowych SAP. Proszę uzupełnić dane i spróbować ponownie przekazać wniosek do dyspozytury.')
        cy.get('button#sendToRealizationError-noBtn').click().should('not.exist')

        cy.log('Krok 16 - Ponawiam krok 7 po przypisaniu kolejno odcinka 3 i 4')
        e50201.audycjePierwszyPrzycisk().click()
        e50201.audycjaPopupPrzyciskWyboru(0).uncheck()
        e50201.audycjaPopupPrzyciskWyboru(2).check()
        e50201.potwierdzAudycjePopupPrzycisk().click()
        e50201.zlozZamowieniePrzycisk().click()
        e50201.takZlozPopupPrzycisk().click()
        cy.get('div#sendToRealizationErrorContainer').contains('W sekcji Technika studyjna, w dniu 26.09.2024 wskazano audycję, która nie ma uzupełnionych identyfikatorów obiektów kontrolingowych SAP. Proszę uzupełnić dane i spróbować ponownie przekazać wniosek do dyspozytury.')
        cy.get('button#sendToRealizationError-noBtn').click().should('not.exist')
        e50201.audycjePierwszyPrzycisk().click()
        e50201.audycjaPopupPrzyciskWyboru(2).uncheck()
        e50201.audycjaPopupPrzyciskWyboru(3).check()
        e50201.potwierdzAudycjePopupPrzycisk().click()
        e50201.zlozZamowieniePrzycisk().click()
        e50201.takZlozPopupPrzycisk().click()
        cy.get('div#sendToRealizationErrorContainer').contains('W sekcji Technika studyjna, w dniu 26.09.2024 wskazano audycję, która nie ma uzupełnionych identyfikatorów obiektów kontrolingowych SAP. Proszę uzupełnić dane i spróbować ponownie przekazać wniosek do dyspozytury.')
        cy.get('button#sendToRealizationError-noBtn').click().should('not.exist')

        cy.log('Krok 17 - Przypisuję odcinek 2 i składam zamówienie')
        e50201.audycjePierwszyPrzycisk().click()
        e50201.audycjaPopupPrzyciskWyboru(3).uncheck()
        e50201.audycjaPopupPrzyciskWyboru(1).check()
        e50201.potwierdzAudycjePopupPrzycisk().click()
        e50201.zlozZamowieniePrzycisk().click()
        e50201.takZlozPopupPrzycisk().click()
        fWspolne.sprawdzProgressBar()
        e50201.statusRezerwacjiEtykieta().should('have.value', 'Przekazano do dyspozytury (zamówienie)')

        cy.log('Krok 18 - Przelogowuję się na dyspozytora i odrzucam rezerwację')
        cy.logoutUser()
        cy.loginPracownikDyspozytury()
        cy.goToMenu('Wnioski o przydzielenie zasobów')
        e501.nazwaAudycjiTVPoleTekstowe().type('SEPP-18072')
        e501.wyszukajPrzycisk().click()
        fWspolne.sprawdzProgressBar()
        e501.edytujSekcjeWnioskuPierwszyPrzycisk().click()
        e50200.odrzucPrzycisk().click()
        e50200.takOdrzucPopupPrzycisk().click()
        e50200.powodOdrzuceniaPopupPoleTekstowe().type('odrzucam')
        e50200.potwierdzPopupPrzycisk().click()
        fWspolne.sprawdzProgressBar()
        cy.logoutUser()
    })

    it('Walidacja SAP dla rodzaju: event korporacyjny', () => {
        cy.log('Krok 19 - Przelogowuję się ponownie na producenta i przechodzę do wybranego porozumienia')
        cy.loginProducent()
        cy.goToMenu('Porozumienia')
        e20.nazwaAudycjiTVPoleTekstowe().type('SEPP-18072')
        e20.wyszukajPrzycisk().click()
        fWspolne.sprawdzProgressBar()
        e20.edycjaPierwszyPrzycisk().click()
        fWspolne.sprawdzProgressBar()

        cy.log('Krok 20 - Zmieniam rodzaj porozumienia na: event korporacyjny')
        e22.rodzajPorozumieniaLista().select('event korporacyjny', {force: true})
        e22.agencjaLista().find('option[selected]').should('contain.text', 'AKFiS')
        e22.zapiszPrzycisk().click()
        fWspolne.sprawdzProgressBar()

        cy.log('Krok 21 - Jestem na ekranie listy wniosków o zasoby i przechodzę na ekran edycji wybranego wniosku')
        cy.goToMenu('Wnioski o przydzielenie zasobów')
        e501.nazwaAudycjiTVPoleTekstowe().type('SEPP-18072')
        e501.wyszukajPrzycisk().click()
        fWspolne.sprawdzProgressBar()
        e501.edytujWniosekPierwszyPrzycisk().click()

        cy.log('Krok 22 - Wyszukuję wybraną rezerwację i przechodzę do jej edycji')
        e502.edycjaRezerwacjiPierwszyPrzycisk().click()

        cy.log('Krok 23 - Sprawdzam czy przypisano odcinek nr 2, a następnie składam zamówienie i sprawdzam czy wystąpi walidacja numerów kontrolingowych')
        cy.get('#daysTable > tbody > tr > td:nth-child(6)').should('have.prop', 'outerText', '2')
        e50201.zlozZamowieniePrzycisk().click()
        e50201.takZlozPopupPrzycisk().click()
        cy.get('div#sendToRealizationErrorContainer').contains('W sekcji Technika studyjna, w dniu 26.09.2024 wskazano audycję, która nie ma uzupełnionych identyfikatorów obiektów kontrolingowych SAP. Proszę uzupełnić dane i spróbować ponownie przekazać wniosek do dyspozytury.')
        cy.get('button#sendToRealizationError-noBtn').click().should('not.exist')

        cy.log('Krok 24 - Ponawiam krok 7 po przypisaniu odcinka 4')
        e50201.audycjePierwszyPrzycisk().click()
        e50201.audycjaPopupPrzyciskWyboru(1).uncheck()
        e50201.audycjaPopupPrzyciskWyboru(3).check()
        e50201.potwierdzAudycjePopupPrzycisk().click()
        e50201.zlozZamowieniePrzycisk().click()
        e50201.takZlozPopupPrzycisk().click()
        cy.get('div#sendToRealizationErrorContainer').contains('W sekcji Technika studyjna, w dniu 26.09.2024 wskazano audycję, która nie ma uzupełnionych identyfikatorów obiektów kontrolingowych SAP. Proszę uzupełnić dane i spróbować ponownie przekazać wniosek do dyspozytury.')
        cy.get('button#sendToRealizationError-noBtn').click().should('not.exist')

        cy.log('Krok 25 - Przypisuję odcinek 3 i składam zamówienie')
        e50201.audycjePierwszyPrzycisk().click()
        e50201.audycjaPopupPrzyciskWyboru(3).uncheck()
        e50201.audycjaPopupPrzyciskWyboru(2).check()
        e50201.potwierdzAudycjePopupPrzycisk().click()
        e50201.zlozZamowieniePrzycisk().click()
        e50201.takZlozPopupPrzycisk().click()
        fWspolne.sprawdzProgressBar()
        e50201.statusRezerwacjiEtykieta().should('have.value', 'Przekazano do dyspozytury (zamówienie)')

        cy.log('Krok 26 - Przelogowuję się na dyspozytora i odrzucam rezerwację')
        cy.logoutUser() 
        cy.loginPracownikDyspozytury()
        cy.goToMenu('Wnioski o przydzielenie zasobów')
        e501.nazwaAudycjiTVPoleTekstowe().type('SEPP-18072')
        e501.wyszukajPrzycisk().click()
        fWspolne.sprawdzProgressBar()
        e501.edytujSekcjeWnioskuPierwszyPrzycisk().click()
        e50200.odrzucPrzycisk().click()
        e50200.takOdrzucPopupPrzycisk().click()
        e50200.powodOdrzuceniaPopupPoleTekstowe().type('odrzucam')
        e50200.potwierdzPopupPrzycisk().click()
        fWspolne.sprawdzProgressBar()
        cy.logoutUser()
    })

    it('Walidacja SAP dla rodzaju: kosztorys usług własnych CUP', () => {
        cy.log('Krok 27 - Przelogowuję się ponownie na producenta i przechodzę do wybranego porozumienia')
        cy.loginProducent()
        cy.goToMenu('Porozumienia')
        e20.nazwaAudycjiTVPoleTekstowe().type('SEPP-18072')
        e20.wyszukajPrzycisk().click()
        fWspolne.sprawdzProgressBar()
        e20.edycjaPierwszyPrzycisk().click()
        fWspolne.sprawdzProgressBar()

        cy.log('Krok 28 - Zmieniam rodzaj porozumienia na: kosztorys usług własnych CUP')
        e22.rodzajPorozumieniaLista().select('kosztorys usług własnych CUP', {force: true})
        fWspolne.sprawdzProgressBar()
        e22.rodzajUslugiLista().select('UP - Usługa produkcyjna', {force: true})
        e22.zapiszPrzycisk().click()
        e22.potwierdzZmianeAgencjiPopupPrzycisk().click()
        fWspolne.sprawdzProgressBar()

        cy.log('Krok 29 - Jestem na ekranie listy wniosków o zasoby i przechodzę na ekran edycji wybranego wniosku')
        cy.goToMenu('Wnioski o przydzielenie zasobów')
        e501.nazwaAudycjiTVPoleTekstowe().type('SEPP-18072')
        e501.wyszukajPrzycisk().click()
        fWspolne.sprawdzProgressBar()
        e501.edytujWniosekPierwszyPrzycisk().click()

        cy.log('Krok 30 - Wyszukuję wybraną rezerwację i przechodzę do jej edycji')
        e502.edycjaRezerwacjiPierwszyPrzycisk().click()

        cy.log('Krok 31 - Sprawdzam czy przypisano odcinek nr 3, a następnie przypisuje odcinek 2, składam zamówienie i sprawdzam czy wystąpi walidacja numerów kontrolingowych')
        cy.get('#daysTable > tbody > tr > td:nth-child(6)').should('have.prop', 'outerText', '3')
        e50201.audycjePierwszyPrzycisk().click()
        e50201.audycjaPopupPrzyciskWyboru(2).uncheck()
        e50201.audycjaPopupPrzyciskWyboru(1).check()
        e50201.potwierdzAudycjePopupPrzycisk().click()
        e50201.zlozZamowieniePrzycisk().click()
        e50201.takZlozPopupPrzycisk().click()
        cy.get('div#sendToRealizationErrorContainer').contains('W sekcji Technika studyjna, w dniu 26.09.2024 wskazano audycję, która nie ma uzupełnionych identyfikatorów obiektów kontrolingowych SAP. Proszę uzupełnić dane i spróbować ponownie przekazać wniosek do dyspozytury.')
        cy.get('button#sendToRealizationError-noBtn').click().should('not.exist')

        cy.log('Krok 33 - Przypisuję odcinek 4 i składam zamówienie')
        e50201.audycjePierwszyPrzycisk().click()
        e50201.audycjaPopupPrzyciskWyboru(1).uncheck()
        e50201.audycjaPopupPrzyciskWyboru(3).check()
        e50201.potwierdzAudycjePopupPrzycisk().click()
        e50201.zlozZamowieniePrzycisk().click()
        e50201.takZlozPopupPrzycisk().click()
        fWspolne.sprawdzProgressBar()
        e50201.statusRezerwacjiEtykieta().should('have.value', 'Przekazano do dyspozytury (zamówienie)')

        cy.log('Krok 34 - Przelogowuję się na dyspozytora i odrzucam rezerwację')
        cy.logoutUser()
        cy.loginPracownikDyspozytury()
        cy.goToMenu('Wnioski o przydzielenie zasobów')
        e501.nazwaAudycjiTVPoleTekstowe().type('SEPP-18072')
        e501.wyszukajPrzycisk().click()
        fWspolne.sprawdzProgressBar()
        e501.edytujSekcjeWnioskuPierwszyPrzycisk().click()
        fWspolne.sprawdzProgressBar()
        e50200.modyfikujRezerwacjePrzycisk().click()
        e50201.audycjePierwszyPrzycisk().click()
        e50201.audycjaPopupPrzyciskWyboru(3).uncheck()
        e50201.audycjaPopupPrzyciskWyboru(1).check()
        e50201.potwierdzAudycjePopupPrzycisk().click()
        e50201.odrzucPrzycisk().click()
        e50201.takOdrzucPopupPrzycisk().click()
        e50201.powodOdrzuceniaPopupPoleTekstowe().type('odrzucam')
        e50201.potwierdzPopupPrzycisk().click()
        fWspolne.sprawdzProgressBar()

        cy.log('Krok 35 - Przelogowuję się na Pracownika agencji CUP i zmieniam rodzaj porozumienia na: produkcyjne')
        cy.logoutUser()
        cy.loginPracownikAgencjiCUP()
        cy.goToMenu('Porozumienia')
        e20.nazwaAudycjiTVPoleTekstowe().type('SEPP-18072')
        e20.wyszukajPrzycisk().click()
        fWspolne.sprawdzProgressBar()
        e20.edycjaPierwszyPrzycisk().click()
        fWspolne.sprawdzProgressBar()
        e22.rodzajPorozumieniaLista().select('produkcyjne', {force: true})
        e22.agencjaLista().select('AKFiS', {force: true})
        e22.jednostkaUslugowaLista().select('CUP', {force: true})
        e22.zapiszPrzycisk().click()
        e22.potwierdzZmianeAgencjiPopupPrzycisk().click()
        fWspolne.sprawdzProgressBar()
        cy.logoutUser()
    })
})